
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace FlavorFi.Data
{

using System;
    using System.Collections.Generic;
    
public partial class CompanySite
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public CompanySite()
    {

        this.Accounts = new HashSet<Account>();

        this.CompanySiteSettings = new HashSet<CompanySiteSetting>();

        this.CompanySiteAccountCrossLinks = new HashSet<CompanySiteAccountCrossLink>();

        this.CompanySiteApplicationCrossLinks = new HashSet<CompanySiteApplicationCrossLink>();

        this.CompanySiteModuleCrossLinks = new HashSet<CompanySiteModuleCrossLink>();

        this.DatabaseSyncLogs = new HashSet<DatabaseSyncLog>();

        this.ShopifyAddresses = new HashSet<ShopifyAddress>();

        this.ShopifyCustomers = new HashSet<ShopifyCustomer>();

        this.ShopifyGiftCards = new HashSet<ShopifyGiftCard>();

        this.ShopifyLocations = new HashSet<ShopifyLocation>();

        this.ShopifyMetafields = new HashSet<ShopifyMetafield>();

        this.ShopifyOrders = new HashSet<ShopifyOrder>();

        this.ShopifyOrderLineItems = new HashSet<ShopifyOrderLineItem>();

        this.ShopifyOrderShippingLines = new HashSet<ShopifyOrderShippingLine>();

        this.ShopifyOrderTransactions = new HashSet<ShopifyOrderTransaction>();

        this.ShopifyProducts = new HashSet<ShopifyProduct>();

        this.ShopifyProductVariants = new HashSet<ShopifyProductVariant>();

        this.ShopifyWebhookLogs = new HashSet<ShopifyWebhookLog>();

    }


    public System.Guid Id { get; set; }

    public System.Guid CompanyId { get; set; }

    public string Name { get; set; }

    public string RegistrationCode { get; set; }

    public string ShopifyUrl { get; set; }

    public string ShopifyWebhookUrl { get; set; }

    public string ShopifyDomain { get; set; }

    public string ShopifyApiPublicKey { get; set; }

    public string ShopifyApiSecretKey { get; set; }

    public string ShopifySharedSecret { get; set; }

    public bool IsActive { get; set; }

    public System.DateTimeOffset DateCreated { get; set; }

    public System.DateTime ValidFrom { get; set; }

    public System.DateTime ValidTo { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Account> Accounts { get; set; }

    public virtual Company Company { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<CompanySiteSetting> CompanySiteSettings { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<CompanySiteAccountCrossLink> CompanySiteAccountCrossLinks { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<CompanySiteApplicationCrossLink> CompanySiteApplicationCrossLinks { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<CompanySiteModuleCrossLink> CompanySiteModuleCrossLinks { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<DatabaseSyncLog> DatabaseSyncLogs { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<ShopifyAddress> ShopifyAddresses { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<ShopifyCustomer> ShopifyCustomers { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<ShopifyGiftCard> ShopifyGiftCards { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<ShopifyLocation> ShopifyLocations { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<ShopifyMetafield> ShopifyMetafields { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<ShopifyOrder> ShopifyOrders { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<ShopifyOrderLineItem> ShopifyOrderLineItems { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<ShopifyOrderShippingLine> ShopifyOrderShippingLines { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<ShopifyOrderTransaction> ShopifyOrderTransactions { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<ShopifyProduct> ShopifyProducts { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<ShopifyProductVariant> ShopifyProductVariants { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<ShopifyWebhookLog> ShopifyWebhookLogs { get; set; }

}

}
