
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace FlavorFi.Data
{

using System;
    using System.Collections.Generic;
    
public partial class CompanySiteEmail
{

    public System.Guid Id { get; set; }

    public System.Guid CompanySiteId { get; set; }

    public string Category { get; set; }

    public string Name { get; set; }

    public string Email { get; set; }

    public System.DateTimeOffset DateCreated { get; set; }

}

}
