
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace FlavorFi.Data
{

using System;
    using System.Collections.Generic;
    
public partial class CompanySiteApplicationCrossLink
{

    public System.Guid Id { get; set; }

    public System.Guid CompanySiteId { get; set; }

    public System.Guid ApplicationId { get; set; }

    public string AppApiPublicKey { get; set; }

    public string AppApiSecretKey { get; set; }

    public string AppSharedSecret { get; set; }

    public string Locations { get; set; }

    public bool IsEnabled { get; set; }

    public System.DateTimeOffset DateCreated { get; set; }



    public virtual Application Application { get; set; }

    public virtual CompanySite CompanySite { get; set; }

}

}
