
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace FlavorFi.Data
{

using System;
    using System.Collections.Generic;
    
public partial class FacebookWebhookLog
{

    public System.Guid Id { get; set; }

    public System.Guid CompanySiteId { get; set; }

    public string EntryId { get; set; }

    public string Entry { get; set; }

    public string Type { get; set; }

    public int TimeSent { get; set; }

    public System.DateTimeOffset DateCreated { get; set; }

}

}
