
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace FlavorFi.Data
{

using System;
    using System.Collections.Generic;
    
public partial class ShopifyUser
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public ShopifyUser()
    {

        this.ShopifyGiftCards = new HashSet<ShopifyGiftCard>();

    }


    public System.Guid Id { get; set; }

    public System.Guid CompanySiteId { get; set; }

    public long OriginalShopifyId { get; set; }

    public string Email { get; set; }

    public bool IsAccountOwner { get; set; }

    public bool ReceiveAnnouncements { get; set; }

    public System.DateTimeOffset DateCreated { get; set; }

    public System.DateTime ValidFrom { get; set; }

    public System.DateTime ValidTo { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<ShopifyGiftCard> ShopifyGiftCards { get; set; }

}

}
