
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace FlavorFi.Data
{

using System;
    using System.Collections.Generic;
    
public partial class ShopifyMetafield
{

    public System.Guid Id { get; set; }

    public System.Guid CompanySiteId { get; set; }

    public Nullable<System.Guid> ShopifyCustomCollectionId { get; set; }

    public Nullable<System.Guid> ShopifyCustomerId { get; set; }

    public Nullable<System.Guid> ShopifyProductId { get; set; }

    public long OriginalShopifyId { get; set; }

    public long OriginalShopifyOwnerId { get; set; }

    public string OwnerResource { get; set; }

    public string Namespace { get; set; }

    public string Key { get; set; }

    public string Value { get; set; }

    public string ValueType { get; set; }

    public System.DateTimeOffset CreatedAt { get; set; }

    public System.DateTimeOffset UpdatedAt { get; set; }

    public System.DateTimeOffset DateCreated { get; set; }

    public System.DateTime ValidFrom { get; set; }

    public System.DateTime ValidTo { get; set; }



    public virtual CompanySite CompanySite { get; set; }

    public virtual ShopifyCustomCollection ShopifyCustomCollection { get; set; }

    public virtual ShopifyCustomer ShopifyCustomer { get; set; }

    public virtual ShopifyProduct ShopifyProduct { get; set; }

}

}
