
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace FlavorFi.Data
{

using System;
    using System.Collections.Generic;
    
public partial class ShopifyProductVariant
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public ShopifyProductVariant()
    {

        this.ShopifyOrderLineItems = new HashSet<ShopifyOrderLineItem>();

    }


    public System.Guid Id { get; set; }

    public System.Guid CompanySiteId { get; set; }

    public System.Guid ShopifyProductId { get; set; }

    public long OriginalShopifyId { get; set; }

    public long OriginalShopifyProductId { get; set; }

    public long OriginalShopifyImageId { get; set; }

    public string Title { get; set; }

    public string Sku { get; set; }

    public string Barcode { get; set; }

    public int Position { get; set; }

    public int InventoryQuantity { get; set; }

    public decimal Price { get; set; }

    public decimal CompareAtPrice { get; set; }

    public bool Taxable { get; set; }

    public bool RequiresShipping { get; set; }

    public System.DateTimeOffset CreatedAt { get; set; }

    public System.DateTimeOffset UpdatedAt { get; set; }

    public System.DateTimeOffset DateCreated { get; set; }

    public System.DateTime ValidFrom { get; set; }

    public System.DateTime ValidTo { get; set; }



    public virtual CompanySite CompanySite { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<ShopifyOrderLineItem> ShopifyOrderLineItems { get; set; }

    public virtual ShopifyProduct ShopifyProduct { get; set; }

}

}
