
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace FlavorFi.Data
{

using System;
    using System.Collections.Generic;
    
public partial class ShopifyCustomer
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public ShopifyCustomer()
    {

        this.ShopifyAddresses = new HashSet<ShopifyAddress>();

        this.ShopifyGiftCards = new HashSet<ShopifyGiftCard>();

        this.ShopifyMetafields = new HashSet<ShopifyMetafield>();

        this.ShopifyOrders = new HashSet<ShopifyOrder>();

    }


    public System.Guid Id { get; set; }

    public System.Guid CompanySiteId { get; set; }

    public long OriginalShopifyId { get; set; }

    public long OriginalShopifyLastOrderId { get; set; }

    public string FirstName { get; set; }

    public string LastName { get; set; }

    public string Email { get; set; }

    public int OrderCount { get; set; }

    public decimal TotalSpent { get; set; }

    public bool IsTaxExempt { get; set; }

    public System.DateTimeOffset CreatedAt { get; set; }

    public System.DateTimeOffset UpdatedAt { get; set; }

    public System.DateTimeOffset DateCreated { get; set; }

    public System.DateTime ValidFrom { get; set; }

    public System.DateTime ValidTo { get; set; }



    public virtual CompanySite CompanySite { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<ShopifyAddress> ShopifyAddresses { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<ShopifyGiftCard> ShopifyGiftCards { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<ShopifyMetafield> ShopifyMetafields { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<ShopifyOrder> ShopifyOrders { get; set; }

}

}
