
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace FlavorFi.Data
{

using System;
    using System.Collections.Generic;
    
public partial class ShopifyOrderShippingLine
{

    public System.Guid Id { get; set; }

    public System.Guid CompanySiteId { get; set; }

    public System.Guid ShopifyOrderId { get; set; }

    public long OriginalShopifyId { get; set; }

    public long OriginalShopifyOrderId { get; set; }

    public string Title { get; set; }

    public string Code { get; set; }

    public string Source { get; set; }

    public decimal Price { get; set; }

    public System.DateTimeOffset DateCreated { get; set; }



    public virtual CompanySite CompanySite { get; set; }

    public virtual ShopifyOrder ShopifyOrder { get; set; }

}

}
