
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace FlavorFi.Data
{

using System;
    using System.Collections.Generic;
    
public partial class ShopifyWebhook
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public ShopifyWebhook()
    {

        this.ShopifyWebhookLogs = new HashSet<ShopifyWebhookLog>();

    }


    public System.Guid Id { get; set; }

    public string Event { get; set; }

    public string Topic { get; set; }

    public string Format { get; set; }

    public System.DateTimeOffset DateCreated { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<ShopifyWebhookLog> ShopifyWebhookLogs { get; set; }

}

}
