
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace FlavorFi.Data
{

using System;
    using System.Collections.Generic;
    
public partial class ShopifyWebhookActivityLog
{

    public System.Guid Id { get; set; }

    public System.Guid ShopifyWebhookLogId { get; set; }

    public string Acivity { get; set; }

    public System.DateTimeOffset DateCreated { get; set; }



    public virtual ShopifyWebhookLog ShopifyWebhookLog { get; set; }

}

}
