//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shopify.Admin.Console.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class adminnotification_inbox
    {
        public long notification_id { get; set; }
        public int severity { get; set; }
        public System.DateTime date_added { get; set; }
        public string title { get; set; }
        public string description { get; set; }
        public string url { get; set; }
        public int is_read { get; set; }
        public int is_remove { get; set; }
    }
}
