//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shopify.Admin.Console.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class affiliatepluspayment_offline
    {
        public long id { get; set; }
        public long payment_id { get; set; }
        public long address_id { get; set; }
        public string address_html { get; set; }
        public string transfer_info { get; set; }
        public string message { get; set; }
    
        public virtual affiliateplus_payment affiliateplus_payment { get; set; }
    }
}
