//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shopify.Admin.Console.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class affiliateplus_payment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public affiliateplus_payment()
        {
            this.affiliateplus_credit = new HashSet<affiliateplus_credit>();
            this.affiliateplus_payment_history = new HashSet<affiliateplus_payment_history>();
            this.affiliateplus_payment_paypal = new HashSet<affiliateplus_payment_paypal>();
            this.affiliatepluspayment_bank = new HashSet<affiliatepluspayment_bank>();
            this.affiliatepluspayment_moneybooker = new HashSet<affiliatepluspayment_moneybooker>();
            this.affiliatepluspayment_offline = new HashSet<affiliatepluspayment_offline>();
        }
    
        public long payment_id { get; set; }
        public long account_id { get; set; }
        public string account_name { get; set; }
        public string account_email { get; set; }
        public string payment_method { get; set; }
        public decimal amount { get; set; }
        public decimal fee { get; set; }
        public Nullable<System.DateTime> request_time { get; set; }
        public short status { get; set; }
        public string description { get; set; }
        public string store_ids { get; set; }
        public short is_request { get; set; }
        public short is_payer_fee { get; set; }
        public short is_reduced_balance { get; set; }
        public short is_refund_balance { get; set; }
        public Nullable<decimal> tax_amount { get; set; }
        public Nullable<decimal> amount_incl_tax { get; set; }
        public short is_recurring { get; set; }
    
        public virtual affiliateplus_account affiliateplus_account { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<affiliateplus_credit> affiliateplus_credit { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<affiliateplus_payment_history> affiliateplus_payment_history { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<affiliateplus_payment_paypal> affiliateplus_payment_paypal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<affiliatepluspayment_bank> affiliatepluspayment_bank { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<affiliatepluspayment_moneybooker> affiliatepluspayment_moneybooker { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<affiliatepluspayment_offline> affiliatepluspayment_offline { get; set; }
    }
}
