//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shopify.Admin.Console.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class affiliateplus_payment_verify
    {
        public long verify_id { get; set; }
        public long account_id { get; set; }
        public string payment_method { get; set; }
        public string field { get; set; }
        public string info { get; set; }
        public short verified { get; set; }
    
        public virtual affiliateplus_account affiliateplus_account { get; set; }
    }
}
