//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shopify.Admin.Console.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class affiliatepluspayment_bankaccount
    {
        public long id { get; set; }
        public long account_id { get; set; }
        public string name { get; set; }
        public string address { get; set; }
        public string account_name { get; set; }
        public string account_number { get; set; }
        public string routing_code { get; set; }
        public string swift_code { get; set; }
    
        public virtual affiliateplus_account affiliateplus_account { get; set; }
    }
}
