//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shopify.Admin.Console.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class affiliateplusprogram
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public affiliateplusprogram()
        {
            this.affiliateplusprogram_account = new HashSet<affiliateplusprogram_account>();
            this.affiliateplusprogram_category = new HashSet<affiliateplusprogram_category>();
            this.affiliateplusprogram_joined = new HashSet<affiliateplusprogram_joined>();
            this.affiliateplusprogram_product = new HashSet<affiliateplusprogram_product>();
            this.affiliateplusprogram_value = new HashSet<affiliateplusprogram_value>();
        }
    
        public long program_id { get; set; }
        public string name { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public short status { get; set; }
        public short expire_time { get; set; }
        public int num_account { get; set; }
        public decimal total_sales_amount { get; set; }
        public string commission_type { get; set; }
        public decimal commission { get; set; }
        public string discount_type { get; set; }
        public decimal discount { get; set; }
        public short autojoin { get; set; }
        public short scope { get; set; }
        public string customer_groups { get; set; }
        public short show_in_welcome { get; set; }
        public Nullable<System.DateTime> valid_from { get; set; }
        public Nullable<System.DateTime> valid_to { get; set; }
        public short use_coupon { get; set; }
        public string coupon_pattern { get; set; }
        public string affiliate_type { get; set; }
        public string description { get; set; }
        public string conditions_serialized { get; set; }
        public string actions_serialized { get; set; }
        public short is_process { get; set; }
        public short use_tier_config { get; set; }
        public int max_level { get; set; }
        public string tier_commission { get; set; }
        public short sec_commission { get; set; }
        public string sec_commission_type { get; set; }
        public decimal secondary_commission { get; set; }
        public short sec_discount { get; set; }
        public string sec_discount_type { get; set; }
        public decimal secondary_discount { get; set; }
        public string customer_group_ids { get; set; }
        public short use_sec_tier { get; set; }
        public string sec_tier_commission { get; set; }
        public Nullable<int> priority { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<affiliateplusprogram_account> affiliateplusprogram_account { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<affiliateplusprogram_category> affiliateplusprogram_category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<affiliateplusprogram_joined> affiliateplusprogram_joined { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<affiliateplusprogram_product> affiliateplusprogram_product { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<affiliateplusprogram_value> affiliateplusprogram_value { get; set; }
    }
}
