//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shopify.Admin.Console.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class affiliateplus_action
    {
        public long action_id { get; set; }
        public long account_id { get; set; }
        public string account_email { get; set; }
        public Nullable<long> banner_id { get; set; }
        public string banner_title { get; set; }
        public short type { get; set; }
        public string ip_address { get; set; }
        public short is_unique { get; set; }
        public int is_commission { get; set; }
        public string domain { get; set; }
        public string referer { get; set; }
        public string landing_page { get; set; }
        public long totals { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public Nullable<System.DateTime> updated_time { get; set; }
        public int store_id { get; set; }
        public long direct_link { get; set; }
    
        public virtual core_store core_store { get; set; }
    }
}
