//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shopify.Admin.Console.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class affiliateplus_payment_history
    {
        public long history_id { get; set; }
        public long payment_id { get; set; }
        public short status { get; set; }
        public Nullable<System.DateTime> created_time { get; set; }
        public string description { get; set; }
    
        public virtual affiliateplus_payment affiliateplus_payment { get; set; }
    }
}
