//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shopify.Admin.Console.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class am_feed_field
    {
        public long field_id { get; set; }
        public string code { get; set; }
        public string title { get; set; }
        public string base_attr { get; set; }
        public string default_value { get; set; }
        public string transform { get; set; }
        public string mapping { get; set; }
        public string condition_serialized { get; set; }
    }
}
