//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shopify.Admin.Console.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class api2_acl_attribute
    {
        public long entity_id { get; set; }
        public string user_type { get; set; }
        public string resource_id { get; set; }
        public string operation { get; set; }
        public string allowed_attributes { get; set; }
    }
}
