//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shopify.Admin.Console.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class api2_acl_rule
    {
        public long entity_id { get; set; }
        public long role_id { get; set; }
        public string resource_id { get; set; }
        public string privilege { get; set; }
    
        public virtual api2_acl_role api2_acl_role { get; set; }
    }
}
