//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shopify.Admin.Console.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class api_session
    {
        public long user_id { get; set; }
        public System.DateTime logdate { get; set; }
        public string sessid { get; set; }
    
        public virtual api_user api_user { get; set; }
    }
}
