//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shopify.Admin.Console.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class aw_arep_options
    {
        public long option_id { get; set; }
        public int admin_id { get; set; }
        public string report_id { get; set; }
        public string path { get; set; }
        public string value { get; set; }
    }
}
