//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shopify.Admin.Console.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class aw_hdu3_department_notification
    {
        public long id { get; set; }
        public long department_id { get; set; }
        public string sender { get; set; }
        public string to_admin_new_ticket_email { get; set; }
        public string to_customer_new_ticket_email { get; set; }
        public string to_customer_new_ticket_by_admin_email { get; set; }
        public string to_admin_new_reply_email { get; set; }
        public string to_customer_new_reply_email { get; set; }
        public string to_primary_agent_reassign_email { get; set; }
        public string to_new_assignee_reassign_email { get; set; }
        public string to_customer_ticket_changed { get; set; }
    
        public virtual aw_hdu3_department aw_hdu3_department { get; set; }
    }
}
