//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shopify.Admin.Console.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class aw_hdu3_customer_note
    {
        public long id { get; set; }
        public long initiator_department_agent_id { get; set; }
        public string customer_email { get; set; }
        public string note { get; set; }
        public System.DateTime created_at { get; set; }
    
        public virtual aw_hdu3_department_agent aw_hdu3_department_agent { get; set; }
    }
}
