//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shopify.Admin.Console.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class aw_hdu3_template
    {
        public long id { get; set; }
        public string title { get; set; }
        public byte is_active { get; set; }
        public string store_ids { get; set; }
        public string content { get; set; }
    }
}
