//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shopify.Admin.Console.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class aw_hdu3_department_agent_link
    {
        public long id { get; set; }
        public long department_id { get; set; }
        public long agent_id { get; set; }
    
        public virtual aw_hdu3_department aw_hdu3_department { get; set; }
        public virtual aw_hdu3_department_agent aw_hdu3_department_agent { get; set; }
    }
}
