//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shopify.Admin.Console.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class aw_lib_logger
    {
        public int id { get; set; }
        public string title { get; set; }
        public string severity { get; set; }
        public string content { get; set; }
        public string module { get; set; }
        public string file_info { get; set; }
        public System.DateTime date { get; set; }
    }
}
