//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shopify.Admin.Console.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class bakerloo_report_orders
    {
        public int id { get; set; }
        public int order_id { get; set; }
        public string order_increment_id { get; set; }
        public Nullable<int> customer_id { get; set; }
        public string customer_name { get; set; }
        public string device_order_id { get; set; }
        public Nullable<System.DateTime> order_date { get; set; }
        public string payment_method { get; set; }
        public Nullable<decimal> subtotal { get; set; }
        public Nullable<decimal> tax_amount { get; set; }
        public Nullable<decimal> grand_total { get; set; }
        public Nullable<decimal> cash_amount { get; set; }
        public Nullable<decimal> cc_amount { get; set; }
        public Nullable<decimal> po_amount { get; set; }
        public Nullable<decimal> store_credit_amount { get; set; }
        public decimal total_to_gross { get; set; }
    }
}
