//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shopify.Admin.Console.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class bakerloo_restful_customprice
    {
        public long id { get; set; }
        public long order_id { get; set; }
        public string order_increment_id { get; set; }
        public string admin_user { get; set; }
        public Nullable<int> store_id { get; set; }
        public Nullable<decimal> total_discount { get; set; }
        public Nullable<decimal> grand_total_before_discount { get; set; }
        public Nullable<decimal> grand_total_after_discount { get; set; }
        public System.DateTime created_at { get; set; }
        public System.DateTime updated_at { get; set; }
    }
}
