//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shopify.Admin.Console.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class bakerloo_restful_shifts
    {
        public long id { get; set; }
        public string shift_guid { get; set; }
        public Nullable<long> device_shift_id { get; set; }
        public string device_id { get; set; }
        public string user { get; set; }
        public System.DateTime open_date { get; set; }
        public string open_notes { get; set; }
        public string json_open_currencies { get; set; }
        public System.DateTime close_date { get; set; }
        public string close_notes { get; set; }
        public string json_close_currencies { get; set; }
        public Nullable<decimal> counted_amount { get; set; }
        public Nullable<int> state { get; set; }
        public Nullable<decimal> sales_amount { get; set; }
        public string sales_amount_currency { get; set; }
        public string json_vatbreakdown { get; set; }
        public System.DateTime created_at { get; set; }
        public System.DateTime updated_at { get; set; }
    }
}
