//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shopify.Admin.Console.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class bakerloo_report_sales__totals_by__user
    {
        public int id { get; set; }
        public string admin_user { get; set; }
        public Nullable<System.DateTime> order_date { get; set; }
        public string currency_code { get; set; }
        public string base_currency_code { get; set; }
        public Nullable<decimal> grand_total { get; set; }
        public Nullable<decimal> subtotal { get; set; }
        public Nullable<decimal> tax_amount { get; set; }
        public Nullable<decimal> base_grand_total { get; set; }
        public Nullable<decimal> base_subtotal { get; set; }
        public Nullable<decimal> base_tax_amount { get; set; }
        public Nullable<int> order_qty { get; set; }
    }
}
