//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shopify.Admin.Console.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class bakerloo_restful_debug
    {
        public long debug_id { get; set; }
        public System.DateTime debug_at { get; set; }
        public string request_body { get; set; }
        public string response_body { get; set; }
        public string request_headers { get; set; }
        public string response_headers { get; set; }
        public string request_method { get; set; }
        public Nullable<long> remote_addr { get; set; }
        public string user_agent { get; set; }
        public string resource { get; set; }
        public Nullable<decimal> call_time { get; set; }
        public Nullable<int> response_code { get; set; }
    }
}
