//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shopify.Admin.Console.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class bakerloo_restful_quotes
    {
        public long id { get; set; }
        public string order_guid { get; set; }
        public Nullable<int> store_id { get; set; }
        public string json_payload { get; set; }
        public string json_payload_enc { get; set; }
        public System.DateTime created_at { get; set; }
        public System.DateTime updated_at { get; set; }
        public string customer_email { get; set; }
        public string customer_firstname { get; set; }
        public string customer_lastname { get; set; }
        public string user { get; set; }
        public string auth_user { get; set; }
    }
}
