//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shopify.Admin.Console.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class bakerloo_restful_orders
    {
        public long id { get; set; }
        public string admin_user { get; set; }
        public long order_id { get; set; }
        public string order_increment_id { get; set; }
        public System.DateTime created_at { get; set; }
        public Nullable<decimal> latitude { get; set; }
        public Nullable<decimal> longitude { get; set; }
        public string admin_user_auth { get; set; }
        public string user_agent { get; set; }
        public string device_id { get; set; }
        public string remote_ip { get; set; }
        public Nullable<int> store_id { get; set; }
        public Nullable<decimal> grand_total { get; set; }
        public Nullable<decimal> base_grand_total { get; set; }
        public Nullable<decimal> base_shipping_amount { get; set; }
        public Nullable<decimal> base_tax_amount { get; set; }
        public Nullable<decimal> base_to_global_rate { get; set; }
        public Nullable<decimal> base_to_order_rate { get; set; }
        public string base_currency_code { get; set; }
        public Nullable<decimal> tax_amount { get; set; }
        public Nullable<decimal> store_to_base_rate { get; set; }
        public Nullable<decimal> store_to_order_rate { get; set; }
        public string global_currency_code { get; set; }
        public string order_currency_code { get; set; }
        public string store_currency_code { get; set; }
        public string device_order_id { get; set; }
        public string json_payload { get; set; }
        public string request_url { get; set; }
        public string json_request_headers { get; set; }
        public string fail_message { get; set; }
        public System.DateTime updated_at { get; set; }
        public string json_payload_enc { get; set; }
        public string json_request_headers_enc { get; set; }
        public string customer_signature { get; set; }
        public string customer_signature_enc { get; set; }
        public Nullable<decimal> subtotal { get; set; }
        public Nullable<decimal> base_subtotal { get; set; }
        public string order_guid { get; set; }
        public Nullable<decimal> discount_amount { get; set; }
        public string login_user { get; set; }
        public string login_user_auth { get; set; }
        public string salesperson { get; set; }
        public int uses_default_customer { get; set; }
    }
}
