//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shopify.Admin.Console.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class captcha_log
    {
        public string type { get; set; }
        public string value { get; set; }
        public long count { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
    }
}
