//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shopify.Admin.Console.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class catalog_category_product
    {
        public long category_id { get; set; }
        public long product_id { get; set; }
        public int position { get; set; }
        public System.Guid ssma_rowid { get; set; }
    
        public virtual catalog_category_entity catalog_category_entity { get; set; }
        public virtual catalog_product_entity catalog_product_entity { get; set; }
    }
}
