//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shopify.Admin.Console.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class catalog_product_entity_gallery
    {
        public int value_id { get; set; }
        public int entity_type_id { get; set; }
        public int attribute_id { get; set; }
        public int store_id { get; set; }
        public long entity_id { get; set; }
        public int position { get; set; }
        public string value { get; set; }
    
        public virtual catalog_product_entity catalog_product_entity { get; set; }
        public virtual eav_attribute eav_attribute { get; set; }
        public virtual core_store core_store { get; set; }
    }
}
