//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shopify.Admin.Console.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class catalog_product_flat_1
    {
        public long entity_id { get; set; }
        public int attribute_set_id { get; set; }
        public string type_id { get; set; }
        public Nullable<decimal> actual_cost { get; set; }
        public Nullable<int> allow_open_amount { get; set; }
        public Nullable<decimal> cost { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public string email_template { get; set; }
        public Nullable<decimal> giftcard_amounts { get; set; }
        public Nullable<int> giftcard_type { get; set; }
        public Nullable<short> gift_message_available { get; set; }
        public Nullable<short> gift_wrapping_available { get; set; }
        public Nullable<decimal> gift_wrapping_price { get; set; }
        public short has_options { get; set; }
        public string image { get; set; }
        public string image_label { get; set; }
        public Nullable<short> is_giftcard { get; set; }
        public Nullable<short> is_recurring { get; set; }
        public Nullable<int> is_redeemable { get; set; }
        public Nullable<int> lifetime { get; set; }
        public Nullable<int> links_exist { get; set; }
        public Nullable<int> links_purchased_separately { get; set; }
        public string links_title { get; set; }
        public Nullable<decimal> msrp { get; set; }
        public string msrp_display_actual_price_type { get; set; }
        public Nullable<short> msrp_enabled { get; set; }
        public string name { get; set; }
        public Nullable<System.DateTime> newest_sort { get; set; }
        public Nullable<System.DateTime> news_from_date { get; set; }
        public Nullable<System.DateTime> news_to_date { get; set; }
        public Nullable<decimal> open_amount_max { get; set; }
        public Nullable<decimal> open_amount_min { get; set; }
        public Nullable<decimal> price { get; set; }
        public Nullable<int> price_type { get; set; }
        public Nullable<int> price_view { get; set; }
        public string recurring_profile { get; set; }
        public int required_options { get; set; }
        public Nullable<int> shipment_type { get; set; }
        public string short_description { get; set; }
        public string sku { get; set; }
        public Nullable<int> sku_type { get; set; }
        public string small_image { get; set; }
        public string small_image_label { get; set; }
        public Nullable<System.DateTime> special_from_date { get; set; }
        public Nullable<decimal> special_price { get; set; }
        public Nullable<System.DateTime> special_to_date { get; set; }
        public Nullable<long> tax_class_id { get; set; }
        public string thumbnail { get; set; }
        public string thumbnail_label { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
        public string url_key { get; set; }
        public string url_path { get; set; }
        public Nullable<int> use_config_email_template { get; set; }
        public Nullable<int> use_config_is_redeemable { get; set; }
        public Nullable<int> use_config_lifetime { get; set; }
        public Nullable<int> visibility { get; set; }
        public Nullable<decimal> weight { get; set; }
        public Nullable<int> weight_type { get; set; }
    }
}
