//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shopify.Admin.Console.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class cataloginventory_stock_status_tmp
    {
        public long product_id { get; set; }
        public int website_id { get; set; }
        public int stock_id { get; set; }
        public decimal qty { get; set; }
        public int stock_status { get; set; }
    }
}
