//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shopify.Admin.Console.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class catalog_product_bundle_selection
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public catalog_product_bundle_selection()
        {
            this.catalog_product_bundle_selection_price = new HashSet<catalog_product_bundle_selection_price>();
        }
    
        public long selection_id { get; set; }
        public long option_id { get; set; }
        public long parent_product_id { get; set; }
        public long product_id { get; set; }
        public long position { get; set; }
        public int is_default { get; set; }
        public int selection_price_type { get; set; }
        public decimal selection_price_value { get; set; }
        public Nullable<decimal> selection_qty { get; set; }
        public short selection_can_change_qty { get; set; }
        public System.Guid ssma_rowid { get; set; }
    
        public virtual catalog_product_bundle_option catalog_product_bundle_option { get; set; }
        public virtual catalog_product_entity catalog_product_entity { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<catalog_product_bundle_selection_price> catalog_product_bundle_selection_price { get; set; }
    }
}
