//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shopify.Admin.Console.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class catalog_product_index_price_bundle_idx
    {
        public long entity_id { get; set; }
        public int customer_group_id { get; set; }
        public int website_id { get; set; }
        public Nullable<int> tax_class_id { get; set; }
        public int price_type { get; set; }
        public Nullable<decimal> special_price { get; set; }
        public Nullable<decimal> tier_percent { get; set; }
        public Nullable<decimal> orig_price { get; set; }
        public Nullable<decimal> price { get; set; }
        public Nullable<decimal> min_price { get; set; }
        public Nullable<decimal> max_price { get; set; }
        public Nullable<decimal> tier_price { get; set; }
        public Nullable<decimal> base_tier { get; set; }
        public Nullable<decimal> group_price { get; set; }
        public Nullable<decimal> base_group_price { get; set; }
        public Nullable<decimal> group_price_percent { get; set; }
    }
}
