//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shopify.Admin.Console.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class catalog_product_option_type_value
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public catalog_product_option_type_value()
        {
            this.catalog_product_option_type_price = new HashSet<catalog_product_option_type_price>();
            this.catalog_product_option_type_title = new HashSet<catalog_product_option_type_title>();
        }
    
        public long option_type_id { get; set; }
        public long option_id { get; set; }
        public string sku { get; set; }
        public long sort_order { get; set; }
    
        public virtual catalog_product_option catalog_product_option { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<catalog_product_option_type_price> catalog_product_option_type_price { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<catalog_product_option_type_title> catalog_product_option_type_title { get; set; }
    }
}
