//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shopify.Admin.Console.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class catalog_product_link
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public catalog_product_link()
        {
            this.catalog_product_link_attribute_decimal = new HashSet<catalog_product_link_attribute_decimal>();
            this.catalog_product_link_attribute_int = new HashSet<catalog_product_link_attribute_int>();
            this.catalog_product_link_attribute_varchar = new HashSet<catalog_product_link_attribute_varchar>();
        }
    
        public long link_id { get; set; }
        public long product_id { get; set; }
        public long linked_product_id { get; set; }
        public int link_type_id { get; set; }
        public System.Guid ssma_rowid { get; set; }
    
        public virtual catalog_product_entity catalog_product_entity { get; set; }
        public virtual catalog_product_link_type catalog_product_link_type { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<catalog_product_link_attribute_decimal> catalog_product_link_attribute_decimal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<catalog_product_link_attribute_int> catalog_product_link_attribute_int { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<catalog_product_link_attribute_varchar> catalog_product_link_attribute_varchar { get; set; }
    }
}
