//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shopify.Admin.Console.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class catalogrule_product
    {
        public long rule_product_id { get; set; }
        public long rule_id { get; set; }
        public long from_time { get; set; }
        public long to_time { get; set; }
        public int customer_group_id { get; set; }
        public long product_id { get; set; }
        public string action_operator { get; set; }
        public decimal action_amount { get; set; }
        public short action_stop { get; set; }
        public long sort_order { get; set; }
        public int website_id { get; set; }
        public string sub_simple_action { get; set; }
        public decimal sub_discount_amount { get; set; }
    
        public virtual catalog_product_entity catalog_product_entity { get; set; }
        public virtual catalogrule catalogrule { get; set; }
        public virtual core_website core_website { get; set; }
        public virtual customer_group customer_group { get; set; }
    }
}
