//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shopify.Admin.Console.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class catalog_product_entity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public catalog_product_entity()
        {
            this.affiliateplusprogram_product = new HashSet<affiliateplusprogram_product>();
            this.catalog_category_product = new HashSet<catalog_category_product>();
            this.catalog_category_product_index = new HashSet<catalog_category_product_index>();
            this.catalog_compare_item = new HashSet<catalog_compare_item>();
            this.catalog_product_bundle_option = new HashSet<catalog_product_bundle_option>();
            this.catalog_product_bundle_price_index = new HashSet<catalog_product_bundle_price_index>();
            this.catalog_product_bundle_selection = new HashSet<catalog_product_bundle_selection>();
            this.catalog_product_enabled_index = new HashSet<catalog_product_enabled_index>();
            this.catalog_product_entity_datetime = new HashSet<catalog_product_entity_datetime>();
            this.catalog_product_entity_decimal = new HashSet<catalog_product_entity_decimal>();
            this.catalog_product_entity_gallery = new HashSet<catalog_product_entity_gallery>();
            this.catalog_product_entity_group_price = new HashSet<catalog_product_entity_group_price>();
            this.catalog_product_entity_int = new HashSet<catalog_product_entity_int>();
            this.catalog_product_entity_media_gallery = new HashSet<catalog_product_entity_media_gallery>();
            this.catalog_product_entity_text = new HashSet<catalog_product_entity_text>();
            this.catalog_product_entity_tier_price = new HashSet<catalog_product_entity_tier_price>();
            this.catalog_product_entity_url_key = new HashSet<catalog_product_entity_url_key>();
            this.catalog_product_entity_varchar = new HashSet<catalog_product_entity_varchar>();
            this.catalog_product_index_eav = new HashSet<catalog_product_index_eav>();
            this.catalog_product_index_eav_decimal = new HashSet<catalog_product_index_eav_decimal>();
            this.catalog_product_index_group_price = new HashSet<catalog_product_index_group_price>();
            this.catalog_product_index_price = new HashSet<catalog_product_index_price>();
            this.catalog_product_index_tier_price = new HashSet<catalog_product_index_tier_price>();
            this.catalog_product_link = new HashSet<catalog_product_link>();
            this.catalog_product_option = new HashSet<catalog_product_option>();
            this.catalog_product_relation = new HashSet<catalog_product_relation>();
            this.catalog_product_super_attribute = new HashSet<catalog_product_super_attribute>();
            this.catalog_product_super_link = new HashSet<catalog_product_super_link>();
            this.catalog_product_website = new HashSet<catalog_product_website>();
            this.cataloginventory_stock_item = new HashSet<cataloginventory_stock_item>();
            this.cataloginventory_stock_status = new HashSet<cataloginventory_stock_status>();
            this.catalogrule_product = new HashSet<catalogrule_product>();
            this.catalogrule_product_price = new HashSet<catalogrule_product_price>();
            this.catalogsearch_result = new HashSet<catalogsearch_result>();
            this.core_url_rewrite = new HashSet<core_url_rewrite>();
            this.downloadable_link = new HashSet<downloadable_link>();
            this.downloadable_sample = new HashSet<downloadable_sample>();
            this.enterprise_catalogpermissions_index_product = new HashSet<enterprise_catalogpermissions_index_product>();
            this.enterprise_giftcard_amount = new HashSet<enterprise_giftcard_amount>();
            this.enterprise_giftregistry_item = new HashSet<enterprise_giftregistry_item>();
            this.enterprise_targetrule_index = new HashSet<enterprise_targetrule_index>();
            this.enterprise_targetrule_index_crosssell = new HashSet<enterprise_targetrule_index_crosssell>();
            this.enterprise_targetrule_index_related = new HashSet<enterprise_targetrule_index_related>();
            this.enterprise_targetrule_index_upsell = new HashSet<enterprise_targetrule_index_upsell>();
            this.enterprise_targetrule_product = new HashSet<enterprise_targetrule_product>();
            this.enterprise_url_rewrite_redirect = new HashSet<enterprise_url_rewrite_redirect>();
            this.levementum_catalog_stock_log = new HashSet<levementum_catalog_stock_log>();
            this.outofstocksubscription_info = new HashSet<outofstocksubscription_info>();
            this.product_alert_price = new HashSet<product_alert_price>();
            this.product_alert_stock = new HashSet<product_alert_stock>();
            this.report_compared_product_index = new HashSet<report_compared_product_index>();
            this.report_viewed_product_aggregated_daily = new HashSet<report_viewed_product_aggregated_daily>();
            this.report_viewed_product_aggregated_monthly = new HashSet<report_viewed_product_aggregated_monthly>();
            this.report_viewed_product_aggregated_yearly = new HashSet<report_viewed_product_aggregated_yearly>();
            this.report_viewed_product_index = new HashSet<report_viewed_product_index>();
            this.sales_bestsellers_aggregated_daily = new HashSet<sales_bestsellers_aggregated_daily>();
            this.sales_bestsellers_aggregated_monthly = new HashSet<sales_bestsellers_aggregated_monthly>();
            this.sales_bestsellers_aggregated_yearly = new HashSet<sales_bestsellers_aggregated_yearly>();
            this.sales_flat_quote_item = new HashSet<sales_flat_quote_item>();
            this.seosuite_report_product = new HashSet<seosuite_report_product>();
            this.tag_relation = new HashSet<tag_relation>();
            this.weee_discount = new HashSet<weee_discount>();
            this.weee_tax = new HashSet<weee_tax>();
            this.wishlist_item = new HashSet<wishlist_item>();
            this.core_website = new HashSet<core_website>();
        }
    
        public long entity_id { get; set; }
        public int entity_type_id { get; set; }
        public int attribute_set_id { get; set; }
        public string type_id { get; set; }
        public string sku { get; set; }
        public short has_options { get; set; }
        public int required_options { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
        public System.Guid ssma_rowid { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<affiliateplusprogram_product> affiliateplusprogram_product { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<catalog_category_product> catalog_category_product { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<catalog_category_product_index> catalog_category_product_index { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<catalog_compare_item> catalog_compare_item { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<catalog_product_bundle_option> catalog_product_bundle_option { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<catalog_product_bundle_price_index> catalog_product_bundle_price_index { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<catalog_product_bundle_selection> catalog_product_bundle_selection { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<catalog_product_enabled_index> catalog_product_enabled_index { get; set; }
        public virtual eav_attribute_set eav_attribute_set { get; set; }
        public virtual eav_entity_type eav_entity_type { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<catalog_product_entity_datetime> catalog_product_entity_datetime { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<catalog_product_entity_decimal> catalog_product_entity_decimal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<catalog_product_entity_gallery> catalog_product_entity_gallery { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<catalog_product_entity_group_price> catalog_product_entity_group_price { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<catalog_product_entity_int> catalog_product_entity_int { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<catalog_product_entity_media_gallery> catalog_product_entity_media_gallery { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<catalog_product_entity_text> catalog_product_entity_text { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<catalog_product_entity_tier_price> catalog_product_entity_tier_price { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<catalog_product_entity_url_key> catalog_product_entity_url_key { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<catalog_product_entity_varchar> catalog_product_entity_varchar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<catalog_product_index_eav> catalog_product_index_eav { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<catalog_product_index_eav_decimal> catalog_product_index_eav_decimal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<catalog_product_index_group_price> catalog_product_index_group_price { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<catalog_product_index_price> catalog_product_index_price { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<catalog_product_index_tier_price> catalog_product_index_tier_price { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<catalog_product_link> catalog_product_link { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<catalog_product_option> catalog_product_option { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<catalog_product_relation> catalog_product_relation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<catalog_product_super_attribute> catalog_product_super_attribute { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<catalog_product_super_link> catalog_product_super_link { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<catalog_product_website> catalog_product_website { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cataloginventory_stock_item> cataloginventory_stock_item { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cataloginventory_stock_status> cataloginventory_stock_status { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<catalogrule_product> catalogrule_product { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<catalogrule_product_price> catalogrule_product_price { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<catalogsearch_result> catalogsearch_result { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<core_url_rewrite> core_url_rewrite { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<downloadable_link> downloadable_link { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<downloadable_sample> downloadable_sample { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<enterprise_catalogpermissions_index_product> enterprise_catalogpermissions_index_product { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<enterprise_giftcard_amount> enterprise_giftcard_amount { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<enterprise_giftregistry_item> enterprise_giftregistry_item { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<enterprise_targetrule_index> enterprise_targetrule_index { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<enterprise_targetrule_index_crosssell> enterprise_targetrule_index_crosssell { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<enterprise_targetrule_index_related> enterprise_targetrule_index_related { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<enterprise_targetrule_index_upsell> enterprise_targetrule_index_upsell { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<enterprise_targetrule_product> enterprise_targetrule_product { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<enterprise_url_rewrite_redirect> enterprise_url_rewrite_redirect { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<levementum_catalog_stock_log> levementum_catalog_stock_log { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<outofstocksubscription_info> outofstocksubscription_info { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<product_alert_price> product_alert_price { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<product_alert_stock> product_alert_stock { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<report_compared_product_index> report_compared_product_index { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<report_viewed_product_aggregated_daily> report_viewed_product_aggregated_daily { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<report_viewed_product_aggregated_monthly> report_viewed_product_aggregated_monthly { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<report_viewed_product_aggregated_yearly> report_viewed_product_aggregated_yearly { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<report_viewed_product_index> report_viewed_product_index { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sales_bestsellers_aggregated_daily> sales_bestsellers_aggregated_daily { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sales_bestsellers_aggregated_monthly> sales_bestsellers_aggregated_monthly { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sales_bestsellers_aggregated_yearly> sales_bestsellers_aggregated_yearly { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sales_flat_quote_item> sales_flat_quote_item { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<seosuite_report_product> seosuite_report_product { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tag_relation> tag_relation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<weee_discount> weee_discount { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<weee_tax> weee_tax { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<wishlist_item> wishlist_item { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<core_website> core_website { get; set; }
    }
}
