//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shopify.Admin.Console.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class catalog_product_entity_media_gallery
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public catalog_product_entity_media_gallery()
        {
            this.catalog_product_entity_media_gallery_value = new HashSet<catalog_product_entity_media_gallery_value>();
        }
    
        public long value_id { get; set; }
        public int attribute_id { get; set; }
        public long entity_id { get; set; }
        public string value { get; set; }
    
        public virtual catalog_product_entity catalog_product_entity { get; set; }
        public virtual eav_attribute eav_attribute { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<catalog_product_entity_media_gallery_value> catalog_product_entity_media_gallery_value { get; set; }
    }
}
