//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shopify.Admin.Console.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class catalog_product_bundle_price_index
    {
        public long entity_id { get; set; }
        public int website_id { get; set; }
        public int customer_group_id { get; set; }
        public decimal min_price { get; set; }
        public decimal max_price { get; set; }
    
        public virtual customer_group customer_group { get; set; }
        public virtual catalog_product_entity catalog_product_entity { get; set; }
        public virtual core_website core_website { get; set; }
    }
}
