//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shopify.Admin.Console.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class catalog_product_bundle_option_value
    {
        public long value_id { get; set; }
        public long option_id { get; set; }
        public int store_id { get; set; }
        public string title { get; set; }
    
        public virtual catalog_product_bundle_option catalog_product_bundle_option { get; set; }
    }
}
