//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shopify.Admin.Console.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class catalogsearch_fulltext
    {
        public long fulltext_id { get; set; }
        public long product_id { get; set; }
        public int store_id { get; set; }
        public string data_index { get; set; }
    }
}
