//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shopify.Admin.Console.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class catalog_product_bundle_stock_index
    {
        public long entity_id { get; set; }
        public int website_id { get; set; }
        public int stock_id { get; set; }
        public long option_id { get; set; }
        public Nullable<short> stock_status { get; set; }
    }
}
