//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shopify.Admin.Console.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class catalog_product_bundle_selection_price
    {
        public long selection_id { get; set; }
        public int website_id { get; set; }
        public int selection_price_type { get; set; }
        public decimal selection_price_value { get; set; }
    
        public virtual catalog_product_bundle_selection catalog_product_bundle_selection { get; set; }
        public virtual core_website core_website { get; set; }
    }
}
