//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shopify.Admin.Console.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class catalogrule_group_website
    {
        public long rule_id { get; set; }
        public int customer_group_id { get; set; }
        public int website_id { get; set; }
    
        public virtual catalogrule catalogrule { get; set; }
        public virtual core_website core_website { get; set; }
        public virtual customer_group customer_group { get; set; }
    }
}
