//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shopify.Admin.Console.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class core_config_data
    {
        public long config_id { get; set; }
        public string scope { get; set; }
        public int scope_id { get; set; }
        public string path { get; set; }
        public string value { get; set; }
    }
}
