//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shopify.Admin.Console.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class core_email_queue_recipients
    {
        public long recipient_id { get; set; }
        public long message_id { get; set; }
        public string recipient_email { get; set; }
        public string recipient_name { get; set; }
        public short email_type { get; set; }
    
        public virtual core_email_queue core_email_queue { get; set; }
    }
}
