//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shopify.Admin.Console.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class core_layout_link
    {
        public long layout_link_id { get; set; }
        public int store_id { get; set; }
        public string area { get; set; }
        public string package { get; set; }
        public string theme { get; set; }
        public long layout_update_id { get; set; }
    
        public virtual core_store core_store { get; set; }
        public virtual core_layout_update core_layout_update { get; set; }
    }
}
