//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shopify.Admin.Console.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class core_cache
    {
        public string id { get; set; }
        public byte[] data { get; set; }
        public Nullable<int> create_time { get; set; }
        public Nullable<int> update_time { get; set; }
        public Nullable<int> expire_time { get; set; }
    }
}
