//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shopify.Admin.Console.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class coupon_aggregated_order
    {
        public long id { get; set; }
        public System.DateTime period { get; set; }
        public Nullable<int> store_id { get; set; }
        public string order_status { get; set; }
        public string coupon_code { get; set; }
        public int coupon_uses { get; set; }
        public decimal subtotal_amount { get; set; }
        public decimal discount_amount { get; set; }
        public decimal total_amount { get; set; }
        public string rule_name { get; set; }
    
        public virtual core_store core_store { get; set; }
    }
}
