//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shopify.Admin.Console.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class crimson_pickqc_item_status_log
    {
        public long log_id { get; set; }
        public long item_status_id { get; set; }
        public Nullable<long> user_id { get; set; }
        public string user_firstname { get; set; }
        public string user_lastname { get; set; }
        public short before_status { get; set; }
        public short status { get; set; }
        public decimal qty_picked { get; set; }
        public short is_override { get; set; }
        public string reason { get; set; }
        public string reason_comment { get; set; }
        public System.DateTime created_at { get; set; }
        public System.DateTime updated_at { get; set; }
    
        public virtual admin_user admin_user { get; set; }
        public virtual crimson_pickqc_item_status crimson_pickqc_item_status { get; set; }
    }
}
