//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shopify.Admin.Console.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class crimson_pickqc_item_status
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public crimson_pickqc_item_status()
        {
            this.crimson_pickqc_item_status_log = new HashSet<crimson_pickqc_item_status_log>();
        }
    
        public long item_status_id { get; set; }
        public long item_parent_id { get; set; }
        public long status_parent_id { get; set; }
        public short status { get; set; }
        public decimal qty_picked { get; set; }
        public System.DateTime created_at { get; set; }
        public System.DateTime updated_at { get; set; }
    
        public virtual crimson_pickqc_status crimson_pickqc_status { get; set; }
        public virtual sales_flat_order_item sales_flat_order_item { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<crimson_pickqc_item_status_log> crimson_pickqc_item_status_log { get; set; }
    }
}
