//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shopify.Admin.Console.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class cron_schedule
    {
        public long schedule_id { get; set; }
        public string job_code { get; set; }
        public string status { get; set; }
        public string messages { get; set; }
        public System.DateTime created_at { get; set; }
        public Nullable<System.DateTime> scheduled_at { get; set; }
        public Nullable<System.DateTime> executed_at { get; set; }
        public Nullable<System.DateTime> finished_at { get; set; }
    }
}
