//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shopify.Admin.Console.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class customer_entity_int
    {
        public int value_id { get; set; }
        public int entity_type_id { get; set; }
        public int attribute_id { get; set; }
        public long entity_id { get; set; }
        public int value { get; set; }
    
        public virtual customer_entity customer_entity { get; set; }
        public virtual eav_entity_type eav_entity_type { get; set; }
        public virtual eav_attribute eav_attribute { get; set; }
    }
}
