//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shopify.Admin.Console.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class customer_entity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public customer_entity()
        {
            this.affiliateplus_account = new HashSet<affiliateplus_account>();
            this.catalog_compare_item = new HashSet<catalog_compare_item>();
            this.customer_address_entity = new HashSet<customer_address_entity>();
            this.customer_entity_datetime = new HashSet<customer_entity_datetime>();
            this.customer_entity_decimal = new HashSet<customer_entity_decimal>();
            this.customer_entity_int = new HashSet<customer_entity_int>();
            this.customer_entity_text = new HashSet<customer_entity_text>();
            this.customer_entity_varchar = new HashSet<customer_entity_varchar>();
            this.downloadable_link_purchased = new HashSet<downloadable_link_purchased>();
            this.enterprise_customerbalance = new HashSet<enterprise_customerbalance>();
            this.enterprise_customersegment_customer = new HashSet<enterprise_customersegment_customer>();
            this.enterprise_giftregistry_entity = new HashSet<enterprise_giftregistry_entity>();
            this.enterprise_invitation = new HashSet<enterprise_invitation>();
            this.enterprise_invitation1 = new HashSet<enterprise_invitation>();
            this.enterprise_invitation_track = new HashSet<enterprise_invitation_track>();
            this.enterprise_reward = new HashSet<enterprise_reward>();
            this.enterprise_rma = new HashSet<enterprise_rma>();
            this.enterprise_sales_order_grid_archive = new HashSet<enterprise_sales_order_grid_archive>();
            this.giftvoucher_credit = new HashSet<giftvoucher_credit>();
            this.giftvoucher_credit_history = new HashSet<giftvoucher_credit_history>();
            this.giftvoucher_customer_voucher = new HashSet<giftvoucher_customer_voucher>();
            this.oauth_token = new HashSet<oauth_token>();
            this.persistent_session = new HashSet<persistent_session>();
            this.product_alert_price = new HashSet<product_alert_price>();
            this.product_alert_stock = new HashSet<product_alert_stock>();
            this.report_compared_product_index = new HashSet<report_compared_product_index>();
            this.report_viewed_product_index = new HashSet<report_viewed_product_index>();
            this.review_detail = new HashSet<review_detail>();
            this.sales_billing_agreement = new HashSet<sales_billing_agreement>();
            this.sales_flat_order = new HashSet<sales_flat_order>();
            this.sales_flat_order_grid = new HashSet<sales_flat_order_grid>();
            this.sales_recurring_profile = new HashSet<sales_recurring_profile>();
            this.salesrule_coupon_usage = new HashSet<salesrule_coupon_usage>();
            this.salesrule_customer = new HashSet<salesrule_customer>();
            this.tags = new HashSet<tag>();
            this.tag_relation = new HashSet<tag_relation>();
            this.wishlists = new HashSet<wishlist>();
        }
    
        public long entity_id { get; set; }
        public int entity_type_id { get; set; }
        public int attribute_set_id { get; set; }
        public Nullable<int> website_id { get; set; }
        public string email { get; set; }
        public int group_id { get; set; }
        public string increment_id { get; set; }
        public Nullable<int> store_id { get; set; }
        public System.DateTime created_at { get; set; }
        public System.DateTime updated_at { get; set; }
        public int is_active { get; set; }
        public int disable_auto_group_change { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<affiliateplus_account> affiliateplus_account { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<catalog_compare_item> catalog_compare_item { get; set; }
        public virtual core_store core_store { get; set; }
        public virtual core_website core_website { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<customer_address_entity> customer_address_entity { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<customer_entity_datetime> customer_entity_datetime { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<customer_entity_decimal> customer_entity_decimal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<customer_entity_int> customer_entity_int { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<customer_entity_text> customer_entity_text { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<customer_entity_varchar> customer_entity_varchar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<downloadable_link_purchased> downloadable_link_purchased { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<enterprise_customerbalance> enterprise_customerbalance { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<enterprise_customersegment_customer> enterprise_customersegment_customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<enterprise_giftregistry_entity> enterprise_giftregistry_entity { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<enterprise_invitation> enterprise_invitation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<enterprise_invitation> enterprise_invitation1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<enterprise_invitation_track> enterprise_invitation_track { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<enterprise_reward> enterprise_reward { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<enterprise_rma> enterprise_rma { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<enterprise_sales_order_grid_archive> enterprise_sales_order_grid_archive { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<giftvoucher_credit> giftvoucher_credit { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<giftvoucher_credit_history> giftvoucher_credit_history { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<giftvoucher_customer_voucher> giftvoucher_customer_voucher { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<oauth_token> oauth_token { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<persistent_session> persistent_session { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<product_alert_price> product_alert_price { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<product_alert_stock> product_alert_stock { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<report_compared_product_index> report_compared_product_index { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<report_viewed_product_index> report_viewed_product_index { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<review_detail> review_detail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sales_billing_agreement> sales_billing_agreement { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sales_flat_order> sales_flat_order { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sales_flat_order_grid> sales_flat_order_grid { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sales_recurring_profile> sales_recurring_profile { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<salesrule_coupon_usage> salesrule_coupon_usage { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<salesrule_customer> salesrule_customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tag> tags { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tag_relation> tag_relation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<wishlist> wishlists { get; set; }
    }
}
