//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shopify.Admin.Console.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class customer_group
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public customer_group()
        {
            this.catalog_product_bundle_price_index = new HashSet<catalog_product_bundle_price_index>();
            this.catalog_product_entity_group_price = new HashSet<catalog_product_entity_group_price>();
            this.catalog_product_entity_tier_price = new HashSet<catalog_product_entity_tier_price>();
            this.catalog_product_index_group_price = new HashSet<catalog_product_index_group_price>();
            this.catalog_product_index_price = new HashSet<catalog_product_index_price>();
            this.catalog_product_index_tier_price = new HashSet<catalog_product_index_tier_price>();
            this.catalogrule_group_website = new HashSet<catalogrule_group_website>();
            this.catalogrule_product = new HashSet<catalogrule_product>();
            this.catalogrule_product_price = new HashSet<catalogrule_product_price>();
            this.enterprise_catalogpermissions = new HashSet<enterprise_catalogpermissions>();
            this.enterprise_catalogpermissions_index = new HashSet<enterprise_catalogpermissions_index>();
            this.enterprise_catalogpermissions_index_product = new HashSet<enterprise_catalogpermissions_index_product>();
            this.enterprise_invitation = new HashSet<enterprise_invitation>();
            this.enterprise_targetrule_index = new HashSet<enterprise_targetrule_index>();
            this.enterprise_targetrule_index_crosssell = new HashSet<enterprise_targetrule_index_crosssell>();
            this.enterprise_targetrule_index_related = new HashSet<enterprise_targetrule_index_related>();
            this.enterprise_targetrule_index_upsell = new HashSet<enterprise_targetrule_index_upsell>();
            this.salesrule_product_attribute = new HashSet<salesrule_product_attribute>();
            this.weee_discount = new HashSet<weee_discount>();
            this.catalogrules = new HashSet<catalogrule>();
            this.salesrules = new HashSet<salesrule>();
        }
    
        public int customer_group_id { get; set; }
        public string customer_group_code { get; set; }
        public long tax_class_id { get; set; }
        public string bakerloo_payment_methods { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<catalog_product_bundle_price_index> catalog_product_bundle_price_index { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<catalog_product_entity_group_price> catalog_product_entity_group_price { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<catalog_product_entity_tier_price> catalog_product_entity_tier_price { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<catalog_product_index_group_price> catalog_product_index_group_price { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<catalog_product_index_price> catalog_product_index_price { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<catalog_product_index_tier_price> catalog_product_index_tier_price { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<catalogrule_group_website> catalogrule_group_website { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<catalogrule_product> catalogrule_product { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<catalogrule_product_price> catalogrule_product_price { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<enterprise_catalogpermissions> enterprise_catalogpermissions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<enterprise_catalogpermissions_index> enterprise_catalogpermissions_index { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<enterprise_catalogpermissions_index_product> enterprise_catalogpermissions_index_product { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<enterprise_invitation> enterprise_invitation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<enterprise_targetrule_index> enterprise_targetrule_index { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<enterprise_targetrule_index_crosssell> enterprise_targetrule_index_crosssell { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<enterprise_targetrule_index_related> enterprise_targetrule_index_related { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<enterprise_targetrule_index_upsell> enterprise_targetrule_index_upsell { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<salesrule_product_attribute> salesrule_product_attribute { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<weee_discount> weee_discount { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<catalogrule> catalogrules { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<salesrule> salesrules { get; set; }
    }
}
