//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shopify.Admin.Console.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class dataflow_session
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public dataflow_session()
        {
            this.dataflow_import_data = new HashSet<dataflow_import_data>();
        }
    
        public int session_id { get; set; }
        public int user_id { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public string file { get; set; }
        public string type { get; set; }
        public string direction { get; set; }
        public string comment { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dataflow_import_data> dataflow_import_data { get; set; }
    }
}
