//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shopify.Admin.Console.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class dataflow_import_data
    {
        public int import_id { get; set; }
        public Nullable<int> session_id { get; set; }
        public int serial_number { get; set; }
        public string value { get; set; }
        public int status { get; set; }
    
        public virtual dataflow_session dataflow_session { get; set; }
    }
}
