//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shopify.Admin.Console.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class dataflow_profile_history
    {
        public long history_id { get; set; }
        public long profile_id { get; set; }
        public string action_code { get; set; }
        public long user_id { get; set; }
        public Nullable<System.DateTime> performed_at { get; set; }
    
        public virtual dataflow_profile dataflow_profile { get; set; }
    }
}
