//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shopify.Admin.Console.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class dataflow_batch_import
    {
        public long batch_import_id { get; set; }
        public long batch_id { get; set; }
        public string batch_data { get; set; }
        public int status { get; set; }
    
        public virtual dataflow_batch dataflow_batch { get; set; }
    }
}
