//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shopify.Admin.Console.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class downloadable_link
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public downloadable_link()
        {
            this.downloadable_link_price = new HashSet<downloadable_link_price>();
            this.downloadable_link_title = new HashSet<downloadable_link_title>();
        }
    
        public long link_id { get; set; }
        public long product_id { get; set; }
        public long sort_order { get; set; }
        public Nullable<int> number_of_downloads { get; set; }
        public int is_shareable { get; set; }
        public string link_url { get; set; }
        public string link_file { get; set; }
        public string link_type { get; set; }
        public string sample_url { get; set; }
        public string sample_file { get; set; }
        public string sample_type { get; set; }
    
        public virtual catalog_product_entity catalog_product_entity { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<downloadable_link_price> downloadable_link_price { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<downloadable_link_title> downloadable_link_title { get; set; }
    }
}
