//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shopify.Admin.Console.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class downloadable_link_title
    {
        public long title_id { get; set; }
        public long link_id { get; set; }
        public int store_id { get; set; }
        public string title { get; set; }
    
        public virtual core_store core_store { get; set; }
        public virtual downloadable_link downloadable_link { get; set; }
    }
}
