//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shopify.Admin.Console.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class eav_entity_type
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public eav_entity_type()
        {
            this.catalog_product_entity = new HashSet<catalog_product_entity>();
            this.customer_address_entity_datetime = new HashSet<customer_address_entity_datetime>();
            this.customer_address_entity_decimal = new HashSet<customer_address_entity_decimal>();
            this.customer_address_entity_int = new HashSet<customer_address_entity_int>();
            this.customer_address_entity_text = new HashSet<customer_address_entity_text>();
            this.customer_address_entity_varchar = new HashSet<customer_address_entity_varchar>();
            this.customer_entity_datetime = new HashSet<customer_entity_datetime>();
            this.customer_entity_decimal = new HashSet<customer_entity_decimal>();
            this.customer_entity_int = new HashSet<customer_entity_int>();
            this.customer_entity_text = new HashSet<customer_entity_text>();
            this.customer_entity_varchar = new HashSet<customer_entity_varchar>();
            this.eav_attribute = new HashSet<eav_attribute>();
            this.eav_attribute_set = new HashSet<eav_attribute_set>();
            this.eav_entity = new HashSet<eav_entity>();
            this.eav_entity_datetime = new HashSet<eav_entity_datetime>();
            this.eav_entity_decimal = new HashSet<eav_entity_decimal>();
            this.eav_entity_int = new HashSet<eav_entity_int>();
            this.eav_entity_store = new HashSet<eav_entity_store>();
            this.eav_entity_text = new HashSet<eav_entity_text>();
            this.eav_entity_varchar = new HashSet<eav_entity_varchar>();
            this.enterprise_rma_item_entity_datetime = new HashSet<enterprise_rma_item_entity_datetime>();
            this.enterprise_rma_item_entity_decimal = new HashSet<enterprise_rma_item_entity_decimal>();
            this.enterprise_rma_item_entity_int = new HashSet<enterprise_rma_item_entity_int>();
            this.enterprise_rma_item_entity_text = new HashSet<enterprise_rma_item_entity_text>();
            this.enterprise_rma_item_entity_varchar = new HashSet<enterprise_rma_item_entity_varchar>();
            this.eav_form_type = new HashSet<eav_form_type>();
        }
    
        public int entity_type_id { get; set; }
        public string entity_type_code { get; set; }
        public string entity_model { get; set; }
        public string attribute_model { get; set; }
        public string entity_table { get; set; }
        public string value_table_prefix { get; set; }
        public string entity_id_field { get; set; }
        public int is_data_sharing { get; set; }
        public string data_sharing_key { get; set; }
        public int default_attribute_set_id { get; set; }
        public string increment_model { get; set; }
        public int increment_per_store { get; set; }
        public int increment_pad_length { get; set; }
        public string increment_pad_char { get; set; }
        public string additional_attribute_table { get; set; }
        public string entity_attribute_collection { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<catalog_product_entity> catalog_product_entity { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<customer_address_entity_datetime> customer_address_entity_datetime { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<customer_address_entity_decimal> customer_address_entity_decimal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<customer_address_entity_int> customer_address_entity_int { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<customer_address_entity_text> customer_address_entity_text { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<customer_address_entity_varchar> customer_address_entity_varchar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<customer_entity_datetime> customer_entity_datetime { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<customer_entity_decimal> customer_entity_decimal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<customer_entity_int> customer_entity_int { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<customer_entity_text> customer_entity_text { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<customer_entity_varchar> customer_entity_varchar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<eav_attribute> eav_attribute { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<eav_attribute_set> eav_attribute_set { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<eav_entity> eav_entity { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<eav_entity_datetime> eav_entity_datetime { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<eav_entity_decimal> eav_entity_decimal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<eav_entity_int> eav_entity_int { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<eav_entity_store> eav_entity_store { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<eav_entity_text> eav_entity_text { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<eav_entity_varchar> eav_entity_varchar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<enterprise_rma_item_entity_datetime> enterprise_rma_item_entity_datetime { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<enterprise_rma_item_entity_decimal> enterprise_rma_item_entity_decimal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<enterprise_rma_item_entity_int> enterprise_rma_item_entity_int { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<enterprise_rma_item_entity_text> enterprise_rma_item_entity_text { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<enterprise_rma_item_entity_varchar> enterprise_rma_item_entity_varchar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<eav_form_type> eav_form_type { get; set; }
    }
}
