//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shopify.Admin.Console.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class eav_form_element
    {
        public long element_id { get; set; }
        public int type_id { get; set; }
        public Nullable<int> fieldset_id { get; set; }
        public int attribute_id { get; set; }
        public int sort_order { get; set; }
    
        public virtual eav_attribute eav_attribute { get; set; }
        public virtual eav_form_fieldset eav_form_fieldset { get; set; }
        public virtual eav_form_type eav_form_type { get; set; }
    }
}
