//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shopify.Admin.Console.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class eav_attribute
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public eav_attribute()
        {
            this.catalog_category_entity_datetime = new HashSet<catalog_category_entity_datetime>();
            this.catalog_category_entity_decimal = new HashSet<catalog_category_entity_decimal>();
            this.catalog_category_entity_int = new HashSet<catalog_category_entity_int>();
            this.catalog_category_entity_text = new HashSet<catalog_category_entity_text>();
            this.catalog_category_entity_url_key = new HashSet<catalog_category_entity_url_key>();
            this.catalog_category_entity_varchar = new HashSet<catalog_category_entity_varchar>();
            this.catalog_product_entity_datetime = new HashSet<catalog_product_entity_datetime>();
            this.catalog_product_entity_decimal = new HashSet<catalog_product_entity_decimal>();
            this.catalog_product_entity_gallery = new HashSet<catalog_product_entity_gallery>();
            this.catalog_product_entity_int = new HashSet<catalog_product_entity_int>();
            this.catalog_product_entity_media_gallery = new HashSet<catalog_product_entity_media_gallery>();
            this.catalog_product_entity_text = new HashSet<catalog_product_entity_text>();
            this.catalog_product_entity_url_key = new HashSet<catalog_product_entity_url_key>();
            this.catalog_product_entity_varchar = new HashSet<catalog_product_entity_varchar>();
            this.catalog_product_index_eav = new HashSet<catalog_product_index_eav>();
            this.catalog_product_index_eav_decimal = new HashSet<catalog_product_index_eav_decimal>();
            this.customer_address_entity_datetime = new HashSet<customer_address_entity_datetime>();
            this.customer_address_entity_decimal = new HashSet<customer_address_entity_decimal>();
            this.customer_address_entity_int = new HashSet<customer_address_entity_int>();
            this.customer_address_entity_text = new HashSet<customer_address_entity_text>();
            this.customer_address_entity_varchar = new HashSet<customer_address_entity_varchar>();
            this.customer_eav_attribute_website = new HashSet<customer_eav_attribute_website>();
            this.customer_entity_datetime = new HashSet<customer_entity_datetime>();
            this.customer_entity_decimal = new HashSet<customer_entity_decimal>();
            this.customer_entity_int = new HashSet<customer_entity_int>();
            this.customer_entity_text = new HashSet<customer_entity_text>();
            this.customer_entity_varchar = new HashSet<customer_entity_varchar>();
            this.customer_form_attribute = new HashSet<customer_form_attribute>();
            this.eav_attribute_label = new HashSet<eav_attribute_label>();
            this.eav_attribute_option = new HashSet<eav_attribute_option>();
            this.eav_entity_attribute = new HashSet<eav_entity_attribute>();
            this.eav_form_element = new HashSet<eav_form_element>();
            this.enterprise_giftcard_amount = new HashSet<enterprise_giftcard_amount>();
            this.enterprise_rma_item_eav_attribute_website = new HashSet<enterprise_rma_item_eav_attribute_website>();
            this.enterprise_rma_item_entity_datetime = new HashSet<enterprise_rma_item_entity_datetime>();
            this.enterprise_rma_item_entity_decimal = new HashSet<enterprise_rma_item_entity_decimal>();
            this.enterprise_rma_item_entity_int = new HashSet<enterprise_rma_item_entity_int>();
            this.enterprise_rma_item_entity_text = new HashSet<enterprise_rma_item_entity_text>();
            this.enterprise_rma_item_entity_varchar = new HashSet<enterprise_rma_item_entity_varchar>();
            this.enterprise_rma_item_form_attribute = new HashSet<enterprise_rma_item_form_attribute>();
            this.salesrule_product_attribute = new HashSet<salesrule_product_attribute>();
            this.weee_tax = new HashSet<weee_tax>();
        }
    
        public int attribute_id { get; set; }
        public int entity_type_id { get; set; }
        public string attribute_code { get; set; }
        public string attribute_model { get; set; }
        public string backend_model { get; set; }
        public string backend_type { get; set; }
        public string backend_table { get; set; }
        public string frontend_model { get; set; }
        public string frontend_input { get; set; }
        public string frontend_label { get; set; }
        public string frontend_class { get; set; }
        public string source_model { get; set; }
        public int is_required { get; set; }
        public int is_user_defined { get; set; }
        public string default_value { get; set; }
        public int is_unique { get; set; }
        public string note { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<catalog_category_entity_datetime> catalog_category_entity_datetime { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<catalog_category_entity_decimal> catalog_category_entity_decimal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<catalog_category_entity_int> catalog_category_entity_int { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<catalog_category_entity_text> catalog_category_entity_text { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<catalog_category_entity_url_key> catalog_category_entity_url_key { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<catalog_category_entity_varchar> catalog_category_entity_varchar { get; set; }
        public virtual catalog_eav_attribute catalog_eav_attribute { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<catalog_product_entity_datetime> catalog_product_entity_datetime { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<catalog_product_entity_decimal> catalog_product_entity_decimal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<catalog_product_entity_gallery> catalog_product_entity_gallery { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<catalog_product_entity_int> catalog_product_entity_int { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<catalog_product_entity_media_gallery> catalog_product_entity_media_gallery { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<catalog_product_entity_text> catalog_product_entity_text { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<catalog_product_entity_url_key> catalog_product_entity_url_key { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<catalog_product_entity_varchar> catalog_product_entity_varchar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<catalog_product_index_eav> catalog_product_index_eav { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<catalog_product_index_eav_decimal> catalog_product_index_eav_decimal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<customer_address_entity_datetime> customer_address_entity_datetime { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<customer_address_entity_decimal> customer_address_entity_decimal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<customer_address_entity_int> customer_address_entity_int { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<customer_address_entity_text> customer_address_entity_text { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<customer_address_entity_varchar> customer_address_entity_varchar { get; set; }
        public virtual customer_eav_attribute customer_eav_attribute { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<customer_eav_attribute_website> customer_eav_attribute_website { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<customer_entity_datetime> customer_entity_datetime { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<customer_entity_decimal> customer_entity_decimal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<customer_entity_int> customer_entity_int { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<customer_entity_text> customer_entity_text { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<customer_entity_varchar> customer_entity_varchar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<customer_form_attribute> customer_form_attribute { get; set; }
        public virtual eav_entity_type eav_entity_type { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<eav_attribute_label> eav_attribute_label { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<eav_attribute_option> eav_attribute_option { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<eav_entity_attribute> eav_entity_attribute { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<eav_form_element> eav_form_element { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<enterprise_giftcard_amount> enterprise_giftcard_amount { get; set; }
        public virtual enterprise_rma_item_eav_attribute enterprise_rma_item_eav_attribute { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<enterprise_rma_item_eav_attribute_website> enterprise_rma_item_eav_attribute_website { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<enterprise_rma_item_entity_datetime> enterprise_rma_item_entity_datetime { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<enterprise_rma_item_entity_decimal> enterprise_rma_item_entity_decimal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<enterprise_rma_item_entity_int> enterprise_rma_item_entity_int { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<enterprise_rma_item_entity_text> enterprise_rma_item_entity_text { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<enterprise_rma_item_entity_varchar> enterprise_rma_item_entity_varchar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<enterprise_rma_item_form_attribute> enterprise_rma_item_form_attribute { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<salesrule_product_attribute> salesrule_product_attribute { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<weee_tax> weee_tax { get; set; }
    }
}
