//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shopify.Admin.Console.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class eav_attribute_group
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public eav_attribute_group()
        {
            this.eav_entity_attribute = new HashSet<eav_entity_attribute>();
        }
    
        public int attribute_group_id { get; set; }
        public int attribute_set_id { get; set; }
        public string attribute_group_name { get; set; }
        public short sort_order { get; set; }
        public Nullable<int> default_id { get; set; }
    
        public virtual eav_attribute_set eav_attribute_set { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<eav_entity_attribute> eav_entity_attribute { get; set; }
    }
}
