//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shopify.Admin.Console.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class eav_entity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public eav_entity()
        {
            this.eav_entity_datetime = new HashSet<eav_entity_datetime>();
            this.eav_entity_decimal = new HashSet<eav_entity_decimal>();
            this.eav_entity_int = new HashSet<eav_entity_int>();
            this.eav_entity_text = new HashSet<eav_entity_text>();
            this.eav_entity_varchar = new HashSet<eav_entity_varchar>();
        }
    
        public long entity_id { get; set; }
        public int entity_type_id { get; set; }
        public int attribute_set_id { get; set; }
        public string increment_id { get; set; }
        public long parent_id { get; set; }
        public int store_id { get; set; }
        public System.DateTime created_at { get; set; }
        public System.DateTime updated_at { get; set; }
        public int is_active { get; set; }
    
        public virtual core_store core_store { get; set; }
        public virtual eav_entity_type eav_entity_type { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<eav_entity_datetime> eav_entity_datetime { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<eav_entity_decimal> eav_entity_decimal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<eav_entity_int> eav_entity_int { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<eav_entity_text> eav_entity_text { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<eav_entity_varchar> eav_entity_varchar { get; set; }
    }
}
