//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shopify.Admin.Console.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class enterprise_invitation_status_history
    {
        public long history_id { get; set; }
        public long invitation_id { get; set; }
        public Nullable<System.DateTime> invitation_date { get; set; }
        public string status { get; set; }
    
        public virtual enterprise_invitation enterprise_invitation { get; set; }
    }
}
