//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shopify.Admin.Console.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class enterprise_rma_item_eav_attribute_website
    {
        public int attribute_id { get; set; }
        public int website_id { get; set; }
        public Nullable<int> is_visible { get; set; }
        public Nullable<int> is_required { get; set; }
        public string default_value { get; set; }
        public Nullable<int> multiline_count { get; set; }
    
        public virtual core_website core_website { get; set; }
        public virtual eav_attribute eav_attribute { get; set; }
    }
}
