//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shopify.Admin.Console.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class enterprise_cms_page_revision
    {
        public long revision_id { get; set; }
        public long version_id { get; set; }
        public short page_id { get; set; }
        public string root_template { get; set; }
        public string meta_keywords { get; set; }
        public string meta_description { get; set; }
        public string content_heading { get; set; }
        public string content { get; set; }
        public System.DateTime created_at { get; set; }
        public string layout_update_xml { get; set; }
        public string custom_theme { get; set; }
        public string custom_root_template { get; set; }
        public string custom_layout_update_xml { get; set; }
        public Nullable<System.DateTime> custom_theme_from { get; set; }
        public Nullable<System.DateTime> custom_theme_to { get; set; }
        public Nullable<long> user_id { get; set; }
        public long revision_number { get; set; }
        public string meta_title { get; set; }
    
        public virtual admin_user admin_user { get; set; }
        public virtual cms_page cms_page { get; set; }
        public virtual enterprise_cms_page_version enterprise_cms_page_version { get; set; }
    }
}
