//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shopify.Admin.Console.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class enterprise_customer_sales_flat_quote
    {
        public long entity_id { get; set; }
        public string customer_test_attribute { get; set; }
    
        public virtual sales_flat_quote sales_flat_quote { get; set; }
    }
}
