//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shopify.Admin.Console.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class enterprise_staging_log
    {
        public int log_id { get; set; }
        public long staging_id { get; set; }
        public long ip { get; set; }
        public string action { get; set; }
        public string status { get; set; }
        public short is_backuped { get; set; }
        public System.DateTime created_at { get; set; }
        public int user_id { get; set; }
        public string username { get; set; }
        public int is_admin_notified { get; set; }
        public string additional_data { get; set; }
        public string map { get; set; }
        public Nullable<int> staging_website_id { get; set; }
        public string staging_website_name { get; set; }
        public Nullable<int> master_website_id { get; set; }
        public string master_website_name { get; set; }
    
        public virtual core_website core_website { get; set; }
        public virtual core_website core_website1 { get; set; }
    }
}
