//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shopify.Admin.Console.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class enterprise_giftregistry_type
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public enterprise_giftregistry_type()
        {
            this.enterprise_giftregistry_entity = new HashSet<enterprise_giftregistry_entity>();
            this.enterprise_giftregistry_label = new HashSet<enterprise_giftregistry_label>();
            this.enterprise_giftregistry_type_info = new HashSet<enterprise_giftregistry_type_info>();
        }
    
        public long type_id { get; set; }
        public string code { get; set; }
        public byte[] meta_xml { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<enterprise_giftregistry_entity> enterprise_giftregistry_entity { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<enterprise_giftregistry_label> enterprise_giftregistry_label { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<enterprise_giftregistry_type_info> enterprise_giftregistry_type_info { get; set; }
    }
}
