//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shopify.Admin.Console.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class enterprise_sales_shipment_grid_archive
    {
        public long entity_id { get; set; }
        public Nullable<int> store_id { get; set; }
        public Nullable<decimal> total_qty { get; set; }
        public long order_id { get; set; }
        public Nullable<int> shipment_status { get; set; }
        public string increment_id { get; set; }
        public string order_increment_id { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> order_created_at { get; set; }
        public string shipping_name { get; set; }
    
        public virtual core_store core_store { get; set; }
        public virtual sales_flat_shipment sales_flat_shipment { get; set; }
    }
}
