//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shopify.Admin.Console.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class enterprise_mview_metadata_event
    {
        public long id { get; set; }
        public long mview_event_id { get; set; }
        public long metadata_id { get; set; }
    
        public virtual enterprise_mview_event enterprise_mview_event { get; set; }
        public virtual enterprise_mview_metadata enterprise_mview_metadata { get; set; }
    }
}
