//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shopify.Admin.Console.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class enterprise_scheduled_operations
    {
        public long id { get; set; }
        public string name { get; set; }
        public string operation_type { get; set; }
        public string entity_type { get; set; }
        public string behavior { get; set; }
        public string start_time { get; set; }
        public string freq { get; set; }
        public short force_import { get; set; }
        public string file_info { get; set; }
        public string details { get; set; }
        public string entity_attributes { get; set; }
        public short status { get; set; }
        public short is_success { get; set; }
        public Nullable<System.DateTime> last_run_date { get; set; }
        public string email_receiver { get; set; }
        public string email_sender { get; set; }
        public string email_template { get; set; }
        public string email_copy { get; set; }
        public string email_copy_method { get; set; }
    }
}
