//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shopify.Admin.Console.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class enterprise_giftregistry_item
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public enterprise_giftregistry_item()
        {
            this.enterprise_giftregistry_item_option = new HashSet<enterprise_giftregistry_item_option>();
        }
    
        public long item_id { get; set; }
        public long entity_id { get; set; }
        public long product_id { get; set; }
        public Nullable<decimal> qty { get; set; }
        public Nullable<decimal> qty_fulfilled { get; set; }
        public string note { get; set; }
        public Nullable<System.DateTime> added_at { get; set; }
        public string custom_options { get; set; }
    
        public virtual catalog_product_entity catalog_product_entity { get; set; }
        public virtual enterprise_giftregistry_entity enterprise_giftregistry_entity { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<enterprise_giftregistry_item_option> enterprise_giftregistry_item_option { get; set; }
    }
}
