//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shopify.Admin.Console.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class enterprise_staging
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public enterprise_staging()
        {
            this.enterprise_staging_item = new HashSet<enterprise_staging_item>();
        }
    
        public long staging_id { get; set; }
        public string type { get; set; }
        public Nullable<int> master_website_id { get; set; }
        public int staging_website_id { get; set; }
        public System.DateTime created_at { get; set; }
        public System.DateTime updated_at { get; set; }
        public string status { get; set; }
        public int sort_order { get; set; }
        public Nullable<System.DateTime> merge_scheduling_date { get; set; }
        public string merge_scheduling_map { get; set; }
    
        public virtual core_website core_website { get; set; }
        public virtual core_website core_website1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<enterprise_staging_item> enterprise_staging_item { get; set; }
    }
}
