//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shopify.Admin.Console.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class enterprise_reminder_rule
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public enterprise_reminder_rule()
        {
            this.enterprise_reminder_rule_coupon = new HashSet<enterprise_reminder_rule_coupon>();
            this.enterprise_reminder_rule_log = new HashSet<enterprise_reminder_rule_log>();
            this.enterprise_reminder_template = new HashSet<enterprise_reminder_template>();
            this.core_website = new HashSet<core_website>();
        }
    
        public long rule_id { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public string conditions_serialized { get; set; }
        public string condition_sql { get; set; }
        public int is_active { get; set; }
        public Nullable<long> salesrule_id { get; set; }
        public string schedule { get; set; }
        public string default_label { get; set; }
        public string default_description { get; set; }
        public Nullable<System.DateTime> from_date { get; set; }
        public Nullable<System.DateTime> to_date { get; set; }
    
        public virtual salesrule salesrule { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<enterprise_reminder_rule_coupon> enterprise_reminder_rule_coupon { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<enterprise_reminder_rule_log> enterprise_reminder_rule_log { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<enterprise_reminder_template> enterprise_reminder_template { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<core_website> core_website { get; set; }
    }
}
