//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shopify.Admin.Console.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class enterprise_url_rewrite
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public enterprise_url_rewrite()
        {
            this.enterprise_catalog_category_rewrite = new HashSet<enterprise_catalog_category_rewrite>();
            this.enterprise_catalog_product_rewrite = new HashSet<enterprise_catalog_product_rewrite>();
            this.enterprise_url_rewrite_redirect_rewrite = new HashSet<enterprise_url_rewrite_redirect_rewrite>();
        }
    
        public long url_rewrite_id { get; set; }
        public string request_path { get; set; }
        public string target_path { get; set; }
        public int is_system { get; set; }
        public string guid { get; set; }
        public string identifier { get; set; }
        public long inc { get; set; }
        public long value_id { get; set; }
        public int store_id { get; set; }
        public int entity_type { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<enterprise_catalog_category_rewrite> enterprise_catalog_category_rewrite { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<enterprise_catalog_product_rewrite> enterprise_catalog_product_rewrite { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<enterprise_url_rewrite_redirect_rewrite> enterprise_url_rewrite_redirect_rewrite { get; set; }
    }
}
