//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shopify.Admin.Console.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class enterprise_customersegment_event
    {
        public long segment_id { get; set; }
        public string @event { get; set; }
    
        public virtual enterprise_customersegment_segment enterprise_customersegment_segment { get; set; }
    }
}
