//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shopify.Admin.Console.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class enterprise_giftcardaccount
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public enterprise_giftcardaccount()
        {
            this.enterprise_giftcardaccount_history = new HashSet<enterprise_giftcardaccount_history>();
        }
    
        public long giftcardaccount_id { get; set; }
        public string code { get; set; }
        public short status { get; set; }
        public System.DateTime date_created { get; set; }
        public Nullable<System.DateTime> date_expires { get; set; }
        public int website_id { get; set; }
        public decimal balance { get; set; }
        public short state { get; set; }
        public short is_redeemable { get; set; }
    
        public virtual core_website core_website { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<enterprise_giftcardaccount_history> enterprise_giftcardaccount_history { get; set; }
    }
}
