//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shopify.Admin.Console.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class enterprise_sales_creditmemo_grid_archive
    {
        public long entity_id { get; set; }
        public Nullable<int> store_id { get; set; }
        public Nullable<decimal> store_to_order_rate { get; set; }
        public Nullable<decimal> base_to_order_rate { get; set; }
        public Nullable<decimal> grand_total { get; set; }
        public Nullable<decimal> store_to_base_rate { get; set; }
        public Nullable<decimal> base_to_global_rate { get; set; }
        public Nullable<decimal> base_grand_total { get; set; }
        public long order_id { get; set; }
        public Nullable<int> creditmemo_status { get; set; }
        public Nullable<int> state { get; set; }
        public Nullable<int> invoice_id { get; set; }
        public string store_currency_code { get; set; }
        public string order_currency_code { get; set; }
        public string base_currency_code { get; set; }
        public string global_currency_code { get; set; }
        public string increment_id { get; set; }
        public string order_increment_id { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> order_created_at { get; set; }
        public string billing_name { get; set; }
    
        public virtual core_store core_store { get; set; }
        public virtual sales_flat_creditmemo sales_flat_creditmemo { get; set; }
    }
}
