//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shopify.Admin.Console.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class enterprise_customersegment_customer
    {
        public long segment_id { get; set; }
        public long customer_id { get; set; }
        public System.DateTime added_date { get; set; }
        public System.DateTime updated_date { get; set; }
        public int website_id { get; set; }
    
        public virtual core_website core_website { get; set; }
        public virtual customer_entity customer_entity { get; set; }
        public virtual enterprise_customersegment_segment enterprise_customersegment_segment { get; set; }
    }
}
