//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shopify.Admin.Console.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class enterprise_catalogpermissions_index
    {
        public long category_id { get; set; }
        public int website_id { get; set; }
        public int customer_group_id { get; set; }
        public Nullable<short> grant_catalog_category_view { get; set; }
        public Nullable<short> grant_catalog_product_price { get; set; }
        public Nullable<short> grant_checkout_items { get; set; }
    
        public virtual catalog_category_entity catalog_category_entity { get; set; }
        public virtual core_website core_website { get; set; }
        public virtual customer_group customer_group { get; set; }
    }
}
