//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shopify.Admin.Console.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class enterprise_invitation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public enterprise_invitation()
        {
            this.enterprise_invitation_status_history = new HashSet<enterprise_invitation_status_history>();
        }
    
        public long invitation_id { get; set; }
        public Nullable<long> customer_id { get; set; }
        public Nullable<System.DateTime> invitation_date { get; set; }
        public string email { get; set; }
        public Nullable<long> referral_id { get; set; }
        public string protection_code { get; set; }
        public Nullable<System.DateTime> signup_date { get; set; }
        public int store_id { get; set; }
        public Nullable<int> group_id { get; set; }
        public string message { get; set; }
        public string status { get; set; }
    
        public virtual core_store core_store { get; set; }
        public virtual customer_entity customer_entity { get; set; }
        public virtual customer_entity customer_entity1 { get; set; }
        public virtual customer_group customer_group { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<enterprise_invitation_status_history> enterprise_invitation_status_history { get; set; }
    }
}
