//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shopify.Admin.Console.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class enterprise_targetrule
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public enterprise_targetrule()
        {
            this.enterprise_targetrule_product = new HashSet<enterprise_targetrule_product>();
            this.enterprise_customersegment_segment = new HashSet<enterprise_customersegment_segment>();
        }
    
        public long rule_id { get; set; }
        public string name { get; set; }
        public Nullable<System.DateTime> from_date { get; set; }
        public Nullable<System.DateTime> to_date { get; set; }
        public short is_active { get; set; }
        public string conditions_serialized { get; set; }
        public string actions_serialized { get; set; }
        public int positions_limit { get; set; }
        public int apply_to { get; set; }
        public Nullable<int> sort_order { get; set; }
        public int use_customer_segment { get; set; }
        public string action_select { get; set; }
        public string action_select_bind { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<enterprise_targetrule_product> enterprise_targetrule_product { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<enterprise_customersegment_segment> enterprise_customersegment_segment { get; set; }
    }
}
