//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shopify.Admin.Console.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class enterprise_catalogevent_event
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public enterprise_catalogevent_event()
        {
            this.enterprise_catalogevent_event_image = new HashSet<enterprise_catalogevent_event_image>();
        }
    
        public long event_id { get; set; }
        public Nullable<long> category_id { get; set; }
        public Nullable<System.DateTime> date_start { get; set; }
        public Nullable<System.DateTime> date_end { get; set; }
        public Nullable<int> display_state { get; set; }
        public Nullable<long> sort_order { get; set; }
    
        public virtual catalog_category_entity catalog_category_entity { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<enterprise_catalogevent_event_image> enterprise_catalogevent_event_image { get; set; }
    }
}
