//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shopify.Admin.Console.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class enterprise_cms_increment
    {
        public long increment_id { get; set; }
        public int increment_type { get; set; }
        public long increment_node { get; set; }
        public long increment_level { get; set; }
        public long last_id { get; set; }
    }
}
