//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shopify.Admin.Console.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class enterprise_cms_hierarchy_metadata
    {
        public long node_id { get; set; }
        public short meta_first_last { get; set; }
        public short meta_next_previous { get; set; }
        public short meta_chapter { get; set; }
        public short meta_section { get; set; }
        public int meta_cs_enabled { get; set; }
        public Nullable<int> pager_visibility { get; set; }
        public Nullable<int> pager_frame { get; set; }
        public Nullable<int> pager_jump { get; set; }
        public Nullable<int> menu_visibility { get; set; }
        public int menu_excluded { get; set; }
        public string menu_layout { get; set; }
        public int menu_brief { get; set; }
        public Nullable<int> menu_levels_down { get; set; }
        public Nullable<int> menu_ordered { get; set; }
        public string menu_list_type { get; set; }
        public Nullable<int> top_menu_visibility { get; set; }
        public Nullable<int> top_menu_excluded { get; set; }
    
        public virtual enterprise_cms_hierarchy_node enterprise_cms_hierarchy_node { get; set; }
    }
}
