//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shopify.Admin.Console.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class enterprise_cms_hierarchy_node
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public enterprise_cms_hierarchy_node()
        {
            this.enterprise_cms_hierarchy_node1 = new HashSet<enterprise_cms_hierarchy_node>();
        }
    
        public long node_id { get; set; }
        public Nullable<long> parent_node_id { get; set; }
        public Nullable<short> page_id { get; set; }
        public string identifier { get; set; }
        public string label { get; set; }
        public int level { get; set; }
        public int sort_order { get; set; }
        public string request_url { get; set; }
        public string xpath { get; set; }
        public string scope { get; set; }
        public long scope_id { get; set; }
    
        public virtual cms_page cms_page { get; set; }
        public virtual enterprise_cms_hierarchy_metadata enterprise_cms_hierarchy_metadata { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<enterprise_cms_hierarchy_node> enterprise_cms_hierarchy_node1 { get; set; }
        public virtual enterprise_cms_hierarchy_node enterprise_cms_hierarchy_node2 { get; set; }
    }
}
