//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shopify.Admin.Console.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class enterprise_rma_item_entity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public enterprise_rma_item_entity()
        {
            this.enterprise_rma_item_entity_datetime = new HashSet<enterprise_rma_item_entity_datetime>();
            this.enterprise_rma_item_entity_decimal = new HashSet<enterprise_rma_item_entity_decimal>();
            this.enterprise_rma_item_entity_int = new HashSet<enterprise_rma_item_entity_int>();
            this.enterprise_rma_item_entity_text = new HashSet<enterprise_rma_item_entity_text>();
            this.enterprise_rma_item_entity_varchar = new HashSet<enterprise_rma_item_entity_varchar>();
        }
    
        public long entity_id { get; set; }
        public int entity_type_id { get; set; }
        public int attribute_set_id { get; set; }
        public long rma_entity_id { get; set; }
        public int is_qty_decimal { get; set; }
        public decimal qty_requested { get; set; }
        public Nullable<decimal> qty_authorized { get; set; }
        public Nullable<decimal> qty_approved { get; set; }
        public string status { get; set; }
        public long order_item_id { get; set; }
        public string product_name { get; set; }
        public string product_sku { get; set; }
        public Nullable<decimal> qty_returned { get; set; }
        public string product_admin_name { get; set; }
        public string product_admin_sku { get; set; }
        public string product_options { get; set; }
    
        public virtual enterprise_rma enterprise_rma { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<enterprise_rma_item_entity_datetime> enterprise_rma_item_entity_datetime { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<enterprise_rma_item_entity_decimal> enterprise_rma_item_entity_decimal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<enterprise_rma_item_entity_int> enterprise_rma_item_entity_int { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<enterprise_rma_item_entity_text> enterprise_rma_item_entity_text { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<enterprise_rma_item_entity_varchar> enterprise_rma_item_entity_varchar { get; set; }
    }
}
