//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shopify.Admin.Console.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class enterprise_customerbalance_history
    {
        public long history_id { get; set; }
        public long balance_id { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
        public int action { get; set; }
        public decimal balance_amount { get; set; }
        public decimal balance_delta { get; set; }
        public string additional_info { get; set; }
        public int is_customer_notified { get; set; }
    
        public virtual enterprise_customerbalance enterprise_customerbalance { get; set; }
    }
}
