//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shopify.Admin.Console.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class enterprise_catalogpermissions_index_product
    {
        public long product_id { get; set; }
        public int store_id { get; set; }
        public Nullable<long> category_id { get; set; }
        public int customer_group_id { get; set; }
        public Nullable<short> grant_catalog_category_view { get; set; }
        public Nullable<short> grant_catalog_product_price { get; set; }
        public Nullable<short> grant_checkout_items { get; set; }
        public Nullable<int> is_config { get; set; }
    
        public virtual catalog_category_entity catalog_category_entity { get; set; }
        public virtual catalog_product_entity catalog_product_entity { get; set; }
        public virtual core_store core_store { get; set; }
        public virtual customer_group customer_group { get; set; }
    }
}
