//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shopify.Admin.Console.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class enterprise_support_backup_item
    {
        public long item_id { get; set; }
        public int status { get; set; }
        public int type { get; set; }
        public long size { get; set; }
        public long backup_id { get; set; }
    
        public virtual enterprise_support_backup enterprise_support_backup { get; set; }
    }
}
