//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shopify.Admin.Console.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class enterprise_giftregistry_entity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public enterprise_giftregistry_entity()
        {
            this.enterprise_giftregistry_item = new HashSet<enterprise_giftregistry_item>();
            this.enterprise_giftregistry_person = new HashSet<enterprise_giftregistry_person>();
        }
    
        public long entity_id { get; set; }
        public long type_id { get; set; }
        public long customer_id { get; set; }
        public int website_id { get; set; }
        public int is_public { get; set; }
        public string url_key { get; set; }
        public string title { get; set; }
        public string message { get; set; }
        public byte[] shipping_address { get; set; }
        public string custom_values { get; set; }
        public short is_active { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
    
        public virtual core_website core_website { get; set; }
        public virtual customer_entity customer_entity { get; set; }
        public virtual enterprise_giftregistry_data enterprise_giftregistry_data { get; set; }
        public virtual enterprise_giftregistry_type enterprise_giftregistry_type { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<enterprise_giftregistry_item> enterprise_giftregistry_item { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<enterprise_giftregistry_person> enterprise_giftregistry_person { get; set; }
    }
}
