//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shopify.Admin.Console.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class enterprise_reward_history
    {
        public long history_id { get; set; }
        public long reward_id { get; set; }
        public int website_id { get; set; }
        public Nullable<int> store_id { get; set; }
        public short action { get; set; }
        public Nullable<int> entity { get; set; }
        public long points_balance { get; set; }
        public int points_delta { get; set; }
        public int points_used { get; set; }
        public long points_voided { get; set; }
        public decimal currency_amount { get; set; }
        public decimal currency_delta { get; set; }
        public string base_currency_code { get; set; }
        public string additional_data { get; set; }
        public string comment { get; set; }
        public System.DateTime created_at { get; set; }
        public Nullable<System.DateTime> expired_at_static { get; set; }
        public Nullable<System.DateTime> expired_at_dynamic { get; set; }
        public short is_expired { get; set; }
        public Nullable<long> is_duplicate_of { get; set; }
        public short notification_sent { get; set; }
    
        public virtual core_store core_store { get; set; }
        public virtual core_website core_website { get; set; }
        public virtual enterprise_reward enterprise_reward { get; set; }
    }
}
