//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shopify.Admin.Console.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class enterprise_rma
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public enterprise_rma()
        {
            this.enterprise_rma_item_entity = new HashSet<enterprise_rma_item_entity>();
            this.enterprise_rma_shipping_label = new HashSet<enterprise_rma_shipping_label>();
            this.enterprise_rma_status_history = new HashSet<enterprise_rma_status_history>();
        }
    
        public long entity_id { get; set; }
        public string status { get; set; }
        public int is_active { get; set; }
        public string increment_id { get; set; }
        public Nullable<System.DateTime> date_requested { get; set; }
        public long order_id { get; set; }
        public string order_increment_id { get; set; }
        public Nullable<int> store_id { get; set; }
        public Nullable<long> customer_id { get; set; }
        public string customer_custom_email { get; set; }
        public string protect_code { get; set; }
    
        public virtual core_store core_store { get; set; }
        public virtual customer_entity customer_entity { get; set; }
        public virtual enterprise_rma_grid enterprise_rma_grid { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<enterprise_rma_item_entity> enterprise_rma_item_entity { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<enterprise_rma_shipping_label> enterprise_rma_shipping_label { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<enterprise_rma_status_history> enterprise_rma_status_history { get; set; }
    }
}
