//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shopify.Admin.Console.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class enterprise_logging_event_changes
    {
        public int id { get; set; }
        public string source_name { get; set; }
        public Nullable<int> event_id { get; set; }
        public Nullable<int> source_id { get; set; }
        public string original_data { get; set; }
        public string result_data { get; set; }
    
        public virtual enterprise_logging_event enterprise_logging_event { get; set; }
    }
}
