//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shopify.Admin.Console.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class giftvoucher_credit_history
    {
        public long history_id { get; set; }
        public long customer_id { get; set; }
        public string action { get; set; }
        public Nullable<decimal> currency_balance { get; set; }
        public string giftcard_code { get; set; }
        public Nullable<int> order_id { get; set; }
        public string order_number { get; set; }
        public Nullable<decimal> balance_change { get; set; }
        public string currency { get; set; }
        public Nullable<decimal> base_amount { get; set; }
        public Nullable<decimal> amount { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
    
        public virtual customer_entity customer_entity { get; set; }
    }
}
