//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shopify.Admin.Console.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class giftvoucher_history
    {
        public long history_id { get; set; }
        public long giftvoucher_id { get; set; }
        public short action { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<decimal> amount { get; set; }
        public string currency { get; set; }
        public short status { get; set; }
        public string comments { get; set; }
        public string order_increment_id { get; set; }
        public Nullable<long> order_item_id { get; set; }
        public Nullable<decimal> order_amount { get; set; }
        public string extra_content { get; set; }
        public Nullable<decimal> balance { get; set; }
        public Nullable<int> customer_id { get; set; }
        public string customer_email { get; set; }
    
        public virtual giftvoucher giftvoucher { get; set; }
    }
}
