//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shopify.Admin.Console.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class giftcard_template
    {
        public long giftcard_template_id { get; set; }
        public string template_name { get; set; }
        public string style_color { get; set; }
        public string text_color { get; set; }
        public string caption { get; set; }
        public string notes { get; set; }
        public string images { get; set; }
        public Nullable<short> design_pattern { get; set; }
        public string background_img { get; set; }
        public short status { get; set; }
    }
}
