//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shopify.Admin.Console.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class giftvoucher_product
    {
        public long giftcard_product_id { get; set; }
        public long product_id { get; set; }
        public string conditions_serialized { get; set; }
        public string giftcard_description { get; set; }
        public string actions_serialized { get; set; }
    }
}
