//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shopify.Admin.Console.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class giftvoucher_customer_voucher
    {
        public long customer_voucher_id { get; set; }
        public long customer_id { get; set; }
        public long voucher_id { get; set; }
        public Nullable<System.DateTime> added_date { get; set; }
    
        public virtual customer_entity customer_entity { get; set; }
        public virtual giftvoucher giftvoucher { get; set; }
    }
}
