//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shopify.Admin.Console.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class host_order_assoc
    {
        public int id { get; set; }
        public Nullable<int> order_id { get; set; }
        public Nullable<int> host_id { get; set; }
        public Nullable<decimal> comission { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<int> affiliate_id { get; set; }
    }
}
