//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shopify.Admin.Console.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class index_event
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public index_event()
        {
            this.index_process_event = new HashSet<index_process_event>();
        }
    
        public long event_id { get; set; }
        public string type { get; set; }
        public string entity { get; set; }
        public Nullable<long> entity_pk { get; set; }
        public System.DateTime created_at { get; set; }
        public string old_data { get; set; }
        public string new_data { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<index_process_event> index_process_event { get; set; }
    }
}
