//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shopify.Admin.Console.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class krypson_productinventory
    {
        public long entity_id { get; set; }
        public string sku { get; set; }
        public Nullable<System.DateTime> date_live { get; set; }
        public Nullable<int> start_qty { get; set; }
        public Nullable<int> sold_seven_days { get; set; }
        public Nullable<int> sold_forteen_days { get; set; }
        public Nullable<int> sold_twoone_days { get; set; }
        public Nullable<int> sold_twoeight_days { get; set; }
        public Nullable<int> sold_fourfive_days { get; set; }
        public Nullable<int> sold_sixty_days { get; set; }
        public Nullable<int> sold_ninety_days { get; set; }
        public Nullable<int> total_qty_ordered { get; set; }
        public string image { get; set; }
        public Nullable<long> product_id { get; set; }
        public Nullable<int> qty_remaining { get; set; }
        public Nullable<decimal> cost_per_item { get; set; }
        public Nullable<decimal> price_per_item { get; set; }
        public Nullable<decimal> total_cost { get; set; }
        public Nullable<decimal> total_price { get; set; }
    }
}
