//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shopify.Admin.Console.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class log_customer
    {
        public long log_id { get; set; }
        public Nullable<long> visitor_id { get; set; }
        public int customer_id { get; set; }
        public System.DateTime login_at { get; set; }
        public Nullable<System.DateTime> logout_at { get; set; }
        public int store_id { get; set; }
    }
}
