//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shopify.Admin.Console.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class log_visitor_online
    {
        public long visitor_id { get; set; }
        public string visitor_type { get; set; }
        public long remote_addr { get; set; }
        public Nullable<System.DateTime> first_visit_at { get; set; }
        public Nullable<System.DateTime> last_visit_at { get; set; }
        public Nullable<long> customer_id { get; set; }
        public string last_url { get; set; }
    }
}
