//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shopify.Admin.Console.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class log_visitor
    {
        public long visitor_id { get; set; }
        public string session_id { get; set; }
        public Nullable<System.DateTime> first_visit_at { get; set; }
        public System.DateTime last_visit_at { get; set; }
        public long last_url_id { get; set; }
        public int store_id { get; set; }
    }
}
