//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shopify.Admin.Console.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class m_email_rule
    {
        public int rule_id { get; set; }
        public string title { get; set; }
        public string description { get; set; }
        public int is_active { get; set; }
        public int is_system { get; set; }
        public string conditions_serialized { get; set; }
        public string actions_serialized { get; set; }
        public System.DateTime created_at { get; set; }
        public System.DateTime updated_at { get; set; }
    }
}
