//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shopify.Admin.Console.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class m_email_trigger
    {
        public int trigger_id { get; set; }
        public string title { get; set; }
        public string description { get; set; }
        public string store_ids { get; set; }
        public int is_active { get; set; }
        public Nullable<System.DateTime> active_from { get; set; }
        public Nullable<System.DateTime> active_to { get; set; }
        public string trigger_type { get; set; }
        public string @event { get; set; }
        public string cancellation_event { get; set; }
        public string schedule { get; set; }
        public Nullable<int> run_rule_id { get; set; }
        public Nullable<int> stop_rule_id { get; set; }
        public string sender_email { get; set; }
        public string sender_name { get; set; }
        public string copy_email { get; set; }
        public string ga_source { get; set; }
        public string ga_medium { get; set; }
        public string ga_term { get; set; }
        public string ga_content { get; set; }
        public string ga_name { get; set; }
        public System.DateTime created_at { get; set; }
        public System.DateTime updated_at { get; set; }
    }
}
