//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shopify.Admin.Console.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class m_email_queue
    {
        public int queue_id { get; set; }
        public string status { get; set; }
        public int trigger_id { get; set; }
        public int chain_id { get; set; }
        public string uniq_key { get; set; }
        public string uniq_key_md5 { get; set; }
        public System.DateTime scheduled_at { get; set; }
        public Nullable<System.DateTime> sent_at { get; set; }
        public int attemtps_number { get; set; }
        public string sender_email { get; set; }
        public string sender_name { get; set; }
        public string recipient_email { get; set; }
        public string recipient_name { get; set; }
        public string subject { get; set; }
        public string content { get; set; }
        public string args_serialized { get; set; }
        public System.DateTime created_at { get; set; }
        public System.DateTime updated_at { get; set; }
        public string history { get; set; }
    }
}
