//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shopify.Admin.Console.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class m_mstcore_attachment
    {
        public int attachment_id { get; set; }
        public string uid { get; set; }
        public string entity_type { get; set; }
        public Nullable<int> entity_id { get; set; }
        public string name { get; set; }
        public string type { get; set; }
        public Nullable<int> size { get; set; }
        public byte[] body { get; set; }
    }
}
