//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shopify.Admin.Console.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class m_mstcore_urlrewrite
    {
        public int urlrewrite_id { get; set; }
        public string url_key { get; set; }
        public string module { get; set; }
        public string type { get; set; }
        public Nullable<int> entity_id { get; set; }
    }
}
