//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shopify.Admin.Console.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class magenotification_log
    {
        public long log_id { get; set; }
        public string extension_code { get; set; }
        public string license_type { get; set; }
        public string license_key { get; set; }
        public System.DateTime check_date { get; set; }
        public string sum_code { get; set; }
        public Nullable<short> response_code { get; set; }
        public string expired_time { get; set; }
        public Nullable<short> is_valid { get; set; }
    }
}
