//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shopify.Admin.Console.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class magenotification
    {
        public long magenotification_id { get; set; }
        public string title { get; set; }
        public string description { get; set; }
        public string url { get; set; }
        public int severity { get; set; }
        public Nullable<short> is_read { get; set; }
        public Nullable<short> is_remove { get; set; }
        public string related_extensions { get; set; }
        public System.DateTime added_date { get; set; }
    }
}
