//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shopify.Admin.Console.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class merchandiser_category_values
    {
        public int category_id { get; set; }
        public string heroproducts { get; set; }
        public string attribute_codes { get; set; }
        public string smart_attributes { get; set; }
        public short ruled_only { get; set; }
        public string automatic_sort { get; set; }
    }
}
