//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shopify.Admin.Console.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class newsletter_subscriber
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public newsletter_subscriber()
        {
            this.newsletter_problem = new HashSet<newsletter_problem>();
            this.newsletter_queue_link = new HashSet<newsletter_queue_link>();
        }
    
        public long subscriber_id { get; set; }
        public Nullable<int> store_id { get; set; }
        public Nullable<System.DateTime> change_status_at { get; set; }
        public long customer_id { get; set; }
        public string subscriber_email { get; set; }
        public int subscriber_status { get; set; }
        public string subscriber_confirm_code { get; set; }
    
        public virtual core_store core_store { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<newsletter_problem> newsletter_problem { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<newsletter_queue_link> newsletter_queue_link { get; set; }
    }
}
