//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shopify.Admin.Console.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class newsletter_queue
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public newsletter_queue()
        {
            this.newsletter_problem = new HashSet<newsletter_problem>();
            this.newsletter_queue_link = new HashSet<newsletter_queue_link>();
            this.core_store = new HashSet<core_store>();
        }
    
        public long queue_id { get; set; }
        public long template_id { get; set; }
        public Nullable<int> newsletter_type { get; set; }
        public string newsletter_text { get; set; }
        public string newsletter_styles { get; set; }
        public string newsletter_subject { get; set; }
        public string newsletter_sender_name { get; set; }
        public string newsletter_sender_email { get; set; }
        public long queue_status { get; set; }
        public Nullable<System.DateTime> queue_start_at { get; set; }
        public Nullable<System.DateTime> queue_finish_at { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<newsletter_problem> newsletter_problem { get; set; }
        public virtual newsletter_template newsletter_template { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<newsletter_queue_link> newsletter_queue_link { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<core_store> core_store { get; set; }
    }
}
