//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shopify.Admin.Console.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class oauth_token
    {
        public long entity_id { get; set; }
        public long consumer_id { get; set; }
        public Nullable<long> admin_id { get; set; }
        public Nullable<long> customer_id { get; set; }
        public string type { get; set; }
        public string token { get; set; }
        public string secret { get; set; }
        public string verifier { get; set; }
        public string callback_url { get; set; }
        public int revoked { get; set; }
        public int authorized { get; set; }
        public System.DateTime created_at { get; set; }
    
        public virtual admin_user admin_user { get; set; }
        public virtual customer_entity customer_entity { get; set; }
        public virtual oauth_consumer oauth_consumer { get; set; }
    }
}
