//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shopify.Admin.Console.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class outofstocksubscription_info
    {
        public long id { get; set; }
        public long product_id { get; set; }
        public string email { get; set; }
        public string is_active { get; set; }
        public Nullable<System.DateTime> date { get; set; }
    
        public virtual catalog_product_entity catalog_product_entity { get; set; }
    }
}
