//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shopify.Admin.Console.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class paradoxlabs_stored_card
    {
        public int id { get; set; }
        public Nullable<int> customer_id { get; set; }
        public string customer_email { get; set; }
        public string customer_ip { get; set; }
        public Nullable<int> profile_id { get; set; }
        public Nullable<int> payment_id { get; set; }
        public string method { get; set; }
        public Nullable<short> active { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
        public Nullable<System.DateTime> last_use { get; set; }
        public Nullable<System.DateTime> expires { get; set; }
        public string address { get; set; }
        public string additional { get; set; }
    }
}
