//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shopify.Admin.Console.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class paypal_payment_transaction
    {
        public long transaction_id { get; set; }
        public string txn_id { get; set; }
        public byte[] additional_information { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
    }
}
