//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shopify.Admin.Console.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class paypal_settlement_report
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public paypal_settlement_report()
        {
            this.paypal_settlement_report_row = new HashSet<paypal_settlement_report_row>();
        }
    
        public long report_id { get; set; }
        public Nullable<System.DateTime> report_date { get; set; }
        public string account_id { get; set; }
        public string filename { get; set; }
        public Nullable<System.DateTime> last_modified { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<paypal_settlement_report_row> paypal_settlement_report_row { get; set; }
    }
}
