//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shopify.Admin.Console.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class persistent_session
    {
        public long persistent_id { get; set; }
        public string key { get; set; }
        public Nullable<long> customer_id { get; set; }
        public int website_id { get; set; }
        public string info { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
    
        public virtual core_website core_website { get; set; }
        public virtual customer_entity customer_entity { get; set; }
    }
}
