//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shopify.Admin.Console.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class poll_answer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public poll_answer()
        {
            this.poll_vote = new HashSet<poll_vote>();
        }
    
        public long answer_id { get; set; }
        public long poll_id { get; set; }
        public string answer_title { get; set; }
        public long votes_count { get; set; }
        public short answer_order { get; set; }
    
        public virtual poll poll { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<poll_vote> poll_vote { get; set; }
    }
}
