//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shopify.Admin.Console.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class product_alert_price
    {
        public long alert_price_id { get; set; }
        public long customer_id { get; set; }
        public long product_id { get; set; }
        public decimal price { get; set; }
        public int website_id { get; set; }
        public System.DateTime add_date { get; set; }
        public Nullable<System.DateTime> last_send_date { get; set; }
        public int send_count { get; set; }
        public int status { get; set; }
    
        public virtual catalog_product_entity catalog_product_entity { get; set; }
        public virtual core_website core_website { get; set; }
        public virtual customer_entity customer_entity { get; set; }
    }
}
