//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shopify.Admin.Console.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class productstat
    {
        public int id { get; set; }
        public string sku { get; set; }
        public string name { get; set; }
        public string price { get; set; }
        public string actual_cost { get; set; }
        public string created_at { get; set; }
        public string qty { get; set; }
        public string total { get; set; }
    }
}
