//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shopify.Admin.Console.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class rating_option_vote
    {
        public long vote_id { get; set; }
        public long option_id { get; set; }
        public string remote_ip { get; set; }
        public long remote_ip_long { get; set; }
        public Nullable<long> customer_id { get; set; }
        public long entity_pk_value { get; set; }
        public int rating_id { get; set; }
        public Nullable<long> review_id { get; set; }
        public short percent { get; set; }
        public short value { get; set; }
    
        public virtual rating_option rating_option { get; set; }
        public virtual review review { get; set; }
    }
}
