//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shopify.Admin.Console.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class sales_recurring_profile
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public sales_recurring_profile()
        {
            this.sales_recurring_profile_order = new HashSet<sales_recurring_profile_order>();
        }
    
        public long profile_id { get; set; }
        public string state { get; set; }
        public Nullable<long> customer_id { get; set; }
        public Nullable<int> store_id { get; set; }
        public string method_code { get; set; }
        public System.DateTime created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
        public string reference_id { get; set; }
        public string subscriber_name { get; set; }
        public System.DateTime start_datetime { get; set; }
        public string internal_reference_id { get; set; }
        public string schedule_description { get; set; }
        public Nullable<int> suspension_threshold { get; set; }
        public int bill_failed_later { get; set; }
        public string period_unit { get; set; }
        public Nullable<int> period_frequency { get; set; }
        public Nullable<int> period_max_cycles { get; set; }
        public decimal billing_amount { get; set; }
        public string trial_period_unit { get; set; }
        public Nullable<int> trial_period_frequency { get; set; }
        public Nullable<int> trial_period_max_cycles { get; set; }
        public string trial_billing_amount { get; set; }
        public string currency_code { get; set; }
        public Nullable<decimal> shipping_amount { get; set; }
        public Nullable<decimal> tax_amount { get; set; }
        public Nullable<decimal> init_amount { get; set; }
        public int init_may_fail { get; set; }
        public string order_info { get; set; }
        public string order_item_info { get; set; }
        public string billing_address_info { get; set; }
        public string shipping_address_info { get; set; }
        public string profile_vendor_info { get; set; }
        public string additional_info { get; set; }
    
        public virtual core_store core_store { get; set; }
        public virtual customer_entity customer_entity { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sales_recurring_profile_order> sales_recurring_profile_order { get; set; }
    }
}
