//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shopify.Admin.Console.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class sales_flat_order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public sales_flat_order()
        {
            this.crimson_pickqc_status = new HashSet<crimson_pickqc_status>();
            this.downloadable_link_purchased = new HashSet<downloadable_link_purchased>();
            this.sales_flat_creditmemo = new HashSet<sales_flat_creditmemo>();
            this.sales_flat_invoice = new HashSet<sales_flat_invoice>();
            this.sales_flat_order_address = new HashSet<sales_flat_order_address>();
            this.sales_flat_order_item = new HashSet<sales_flat_order_item>();
            this.sales_flat_order_payment = new HashSet<sales_flat_order_payment>();
            this.sales_flat_order_status_history = new HashSet<sales_flat_order_status_history>();
            this.sales_flat_shipment = new HashSet<sales_flat_shipment>();
            this.sales_payment_transaction = new HashSet<sales_payment_transaction>();
            this.sales_recurring_profile_order = new HashSet<sales_recurring_profile_order>();
            this.tm_orderattachment = new HashSet<tm_orderattachment>();
            this.sales_billing_agreement = new HashSet<sales_billing_agreement>();
        }
    
        public long entity_id { get; set; }
        public string state { get; set; }
        public string status { get; set; }
        public string coupon_code { get; set; }
        public string protect_code { get; set; }
        public string shipping_description { get; set; }
        public Nullable<int> is_virtual { get; set; }
        public Nullable<int> store_id { get; set; }
        public Nullable<long> customer_id { get; set; }
        public Nullable<decimal> base_discount_amount { get; set; }
        public Nullable<decimal> base_discount_canceled { get; set; }
        public Nullable<decimal> base_discount_invoiced { get; set; }
        public Nullable<decimal> base_discount_refunded { get; set; }
        public Nullable<decimal> base_grand_total { get; set; }
        public Nullable<decimal> base_shipping_amount { get; set; }
        public Nullable<decimal> base_shipping_canceled { get; set; }
        public Nullable<decimal> base_shipping_invoiced { get; set; }
        public Nullable<decimal> base_shipping_refunded { get; set; }
        public Nullable<decimal> base_shipping_tax_amount { get; set; }
        public Nullable<decimal> base_shipping_tax_refunded { get; set; }
        public Nullable<decimal> base_subtotal { get; set; }
        public Nullable<decimal> base_subtotal_canceled { get; set; }
        public Nullable<decimal> base_subtotal_invoiced { get; set; }
        public Nullable<decimal> base_subtotal_refunded { get; set; }
        public Nullable<decimal> base_tax_amount { get; set; }
        public Nullable<decimal> base_tax_canceled { get; set; }
        public Nullable<decimal> base_tax_invoiced { get; set; }
        public Nullable<decimal> base_tax_refunded { get; set; }
        public Nullable<decimal> base_to_global_rate { get; set; }
        public Nullable<decimal> base_to_order_rate { get; set; }
        public Nullable<decimal> base_total_canceled { get; set; }
        public Nullable<decimal> base_total_invoiced { get; set; }
        public Nullable<decimal> base_total_invoiced_cost { get; set; }
        public Nullable<decimal> base_total_offline_refunded { get; set; }
        public Nullable<decimal> base_total_online_refunded { get; set; }
        public Nullable<decimal> base_total_paid { get; set; }
        public Nullable<decimal> base_total_qty_ordered { get; set; }
        public Nullable<decimal> base_total_refunded { get; set; }
        public Nullable<decimal> discount_amount { get; set; }
        public Nullable<decimal> discount_canceled { get; set; }
        public Nullable<decimal> discount_invoiced { get; set; }
        public Nullable<decimal> discount_refunded { get; set; }
        public Nullable<decimal> grand_total { get; set; }
        public Nullable<decimal> shipping_amount { get; set; }
        public Nullable<decimal> shipping_canceled { get; set; }
        public Nullable<decimal> shipping_invoiced { get; set; }
        public Nullable<decimal> shipping_refunded { get; set; }
        public Nullable<decimal> shipping_tax_amount { get; set; }
        public Nullable<decimal> shipping_tax_refunded { get; set; }
        public Nullable<decimal> store_to_base_rate { get; set; }
        public Nullable<decimal> store_to_order_rate { get; set; }
        public Nullable<decimal> subtotal { get; set; }
        public Nullable<decimal> subtotal_canceled { get; set; }
        public Nullable<decimal> subtotal_invoiced { get; set; }
        public Nullable<decimal> subtotal_refunded { get; set; }
        public Nullable<decimal> tax_amount { get; set; }
        public Nullable<decimal> tax_canceled { get; set; }
        public Nullable<decimal> tax_invoiced { get; set; }
        public Nullable<decimal> tax_refunded { get; set; }
        public Nullable<decimal> total_canceled { get; set; }
        public Nullable<decimal> total_invoiced { get; set; }
        public Nullable<decimal> total_offline_refunded { get; set; }
        public Nullable<decimal> total_online_refunded { get; set; }
        public Nullable<decimal> total_paid { get; set; }
        public Nullable<decimal> total_qty_ordered { get; set; }
        public Nullable<decimal> total_refunded { get; set; }
        public Nullable<int> can_ship_partially { get; set; }
        public Nullable<int> can_ship_partially_item { get; set; }
        public Nullable<int> customer_is_guest { get; set; }
        public Nullable<int> customer_note_notify { get; set; }
        public Nullable<int> billing_address_id { get; set; }
        public Nullable<short> customer_group_id { get; set; }
        public Nullable<int> edit_increment { get; set; }
        public Nullable<int> email_sent { get; set; }
        public Nullable<int> forced_shipment_with_invoice { get; set; }
        public Nullable<int> payment_auth_expiration { get; set; }
        public Nullable<int> quote_address_id { get; set; }
        public Nullable<int> quote_id { get; set; }
        public Nullable<int> shipping_address_id { get; set; }
        public Nullable<decimal> adjustment_negative { get; set; }
        public Nullable<decimal> adjustment_positive { get; set; }
        public Nullable<decimal> base_adjustment_negative { get; set; }
        public Nullable<decimal> base_adjustment_positive { get; set; }
        public Nullable<decimal> base_shipping_discount_amount { get; set; }
        public Nullable<decimal> base_subtotal_incl_tax { get; set; }
        public Nullable<decimal> base_total_due { get; set; }
        public Nullable<decimal> payment_authorization_amount { get; set; }
        public Nullable<decimal> shipping_discount_amount { get; set; }
        public Nullable<decimal> subtotal_incl_tax { get; set; }
        public Nullable<decimal> total_due { get; set; }
        public Nullable<decimal> weight { get; set; }
        public Nullable<System.DateTime> customer_dob { get; set; }
        public string increment_id { get; set; }
        public string applied_rule_ids { get; set; }
        public string base_currency_code { get; set; }
        public string customer_email { get; set; }
        public string customer_firstname { get; set; }
        public string customer_lastname { get; set; }
        public string customer_middlename { get; set; }
        public string customer_prefix { get; set; }
        public string customer_suffix { get; set; }
        public string customer_taxvat { get; set; }
        public string discount_description { get; set; }
        public string ext_customer_id { get; set; }
        public string ext_order_id { get; set; }
        public string global_currency_code { get; set; }
        public string hold_before_state { get; set; }
        public string hold_before_status { get; set; }
        public string order_currency_code { get; set; }
        public string original_increment_id { get; set; }
        public string relation_child_id { get; set; }
        public string relation_child_real_id { get; set; }
        public string relation_parent_id { get; set; }
        public string relation_parent_real_id { get; set; }
        public string remote_ip { get; set; }
        public string shipping_method { get; set; }
        public string store_currency_code { get; set; }
        public string store_name { get; set; }
        public string x_forwarded_for { get; set; }
        public string customer_note { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
        public int total_item_count { get; set; }
        public Nullable<int> customer_gender { get; set; }
        public Nullable<decimal> hidden_tax_amount { get; set; }
        public Nullable<decimal> base_hidden_tax_amount { get; set; }
        public Nullable<decimal> shipping_hidden_tax_amount { get; set; }
        public Nullable<decimal> base_shipping_hidden_tax_amnt { get; set; }
        public Nullable<decimal> hidden_tax_invoiced { get; set; }
        public Nullable<decimal> base_hidden_tax_invoiced { get; set; }
        public Nullable<decimal> hidden_tax_refunded { get; set; }
        public Nullable<decimal> base_hidden_tax_refunded { get; set; }
        public Nullable<decimal> shipping_incl_tax { get; set; }
        public Nullable<decimal> base_shipping_incl_tax { get; set; }
        public string coupon_rule_name { get; set; }
        public Nullable<int> paypal_ipn_customer_notified { get; set; }
        public Nullable<int> gift_message_id { get; set; }
        public Nullable<decimal> base_customer_balance_amount { get; set; }
        public Nullable<decimal> customer_balance_amount { get; set; }
        public Nullable<decimal> base_customer_balance_invoiced { get; set; }
        public Nullable<decimal> customer_balance_invoiced { get; set; }
        public Nullable<decimal> base_customer_balance_refunded { get; set; }
        public Nullable<decimal> customer_balance_refunded { get; set; }
        public Nullable<decimal> bs_customer_bal_total_refunded { get; set; }
        public Nullable<decimal> customer_bal_total_refunded { get; set; }
        public string gift_cards { get; set; }
        public Nullable<decimal> base_gift_cards_amount { get; set; }
        public Nullable<decimal> gift_cards_amount { get; set; }
        public Nullable<decimal> base_gift_cards_invoiced { get; set; }
        public Nullable<decimal> gift_cards_invoiced { get; set; }
        public Nullable<decimal> base_gift_cards_refunded { get; set; }
        public Nullable<decimal> gift_cards_refunded { get; set; }
        public Nullable<int> gw_id { get; set; }
        public Nullable<int> gw_allow_gift_receipt { get; set; }
        public Nullable<int> gw_add_card { get; set; }
        public Nullable<decimal> gw_base_price { get; set; }
        public Nullable<decimal> gw_price { get; set; }
        public Nullable<decimal> gw_items_base_price { get; set; }
        public Nullable<decimal> gw_items_price { get; set; }
        public Nullable<decimal> gw_card_base_price { get; set; }
        public Nullable<decimal> gw_card_price { get; set; }
        public Nullable<decimal> gw_base_tax_amount { get; set; }
        public Nullable<decimal> gw_tax_amount { get; set; }
        public Nullable<decimal> gw_items_base_tax_amount { get; set; }
        public Nullable<decimal> gw_items_tax_amount { get; set; }
        public Nullable<decimal> gw_card_base_tax_amount { get; set; }
        public Nullable<decimal> gw_card_tax_amount { get; set; }
        public Nullable<decimal> gw_base_price_invoiced { get; set; }
        public Nullable<decimal> gw_price_invoiced { get; set; }
        public Nullable<decimal> gw_items_base_price_invoiced { get; set; }
        public Nullable<decimal> gw_items_price_invoiced { get; set; }
        public Nullable<decimal> gw_card_base_price_invoiced { get; set; }
        public Nullable<decimal> gw_card_price_invoiced { get; set; }
        public Nullable<decimal> gw_base_tax_amount_invoiced { get; set; }
        public Nullable<decimal> gw_tax_amount_invoiced { get; set; }
        public Nullable<decimal> gw_items_base_tax_invoiced { get; set; }
        public Nullable<decimal> gw_items_tax_invoiced { get; set; }
        public Nullable<decimal> gw_card_base_tax_invoiced { get; set; }
        public Nullable<decimal> gw_card_tax_invoiced { get; set; }
        public Nullable<decimal> gw_base_price_refunded { get; set; }
        public Nullable<decimal> gw_price_refunded { get; set; }
        public Nullable<decimal> gw_items_base_price_refunded { get; set; }
        public Nullable<decimal> gw_items_price_refunded { get; set; }
        public Nullable<decimal> gw_card_base_price_refunded { get; set; }
        public Nullable<decimal> gw_card_price_refunded { get; set; }
        public Nullable<decimal> gw_base_tax_amount_refunded { get; set; }
        public Nullable<decimal> gw_tax_amount_refunded { get; set; }
        public Nullable<decimal> gw_items_base_tax_refunded { get; set; }
        public Nullable<decimal> gw_items_tax_refunded { get; set; }
        public Nullable<decimal> gw_card_base_tax_refunded { get; set; }
        public Nullable<decimal> gw_card_tax_refunded { get; set; }
        public Nullable<int> reward_points_balance { get; set; }
        public Nullable<decimal> base_reward_currency_amount { get; set; }
        public Nullable<decimal> reward_currency_amount { get; set; }
        public Nullable<decimal> base_rwrd_crrncy_amt_invoiced { get; set; }
        public Nullable<decimal> rwrd_currency_amount_invoiced { get; set; }
        public Nullable<decimal> base_rwrd_crrncy_amnt_refnded { get; set; }
        public Nullable<decimal> rwrd_crrncy_amnt_refunded { get; set; }
        public Nullable<int> reward_points_balance_refund { get; set; }
        public Nullable<int> reward_points_balance_refunded { get; set; }
        public Nullable<int> reward_salesrule_points { get; set; }
        public Nullable<System.DateTime> firecheckout_delivery_date { get; set; }
        public string firecheckout_delivery_timerange { get; set; }
        public string firecheckout_customer_comment { get; set; }
        public string tm_field1 { get; set; }
        public string tm_field2 { get; set; }
        public string tm_field3 { get; set; }
        public string tm_field4 { get; set; }
        public string tm_field5 { get; set; }
        public string auctaneapi_discounts { get; set; }
        public Nullable<byte> pp_invoice_printed { get; set; }
        public Nullable<byte> pp_packing_sheet_printed { get; set; }
        public Nullable<byte> pp_order_pick_list_printed { get; set; }
        public Nullable<byte> pp_items_pick_list_printed { get; set; }
        public Nullable<decimal> affiliateplus_discount { get; set; }
        public Nullable<decimal> base_affiliateplus_discount { get; set; }
        public Nullable<decimal> base_affiliate_credit { get; set; }
        public Nullable<decimal> affiliate_credit { get; set; }
        public string affiliateplus_coupon { get; set; }
        public Nullable<decimal> payment_charge { get; set; }
        public Nullable<decimal> base_payment_charge { get; set; }
        public Nullable<decimal> base_paypalfee_amount { get; set; }
        public Nullable<decimal> paypalfee_amount { get; set; }
        public Nullable<decimal> base_giftvoucher_discount_for_shipping { get; set; }
        public Nullable<decimal> giftvoucher_discount_for_shipping { get; set; }
        public Nullable<decimal> base_giftcredit_discount_for_shipping { get; set; }
        public Nullable<decimal> giftcredit_discount_for_shipping { get; set; }
        public decimal base_gift_voucher_discount { get; set; }
        public decimal gift_voucher_discount { get; set; }
        public decimal base_use_gift_credit_amount { get; set; }
        public decimal use_gift_credit_amount { get; set; }
        public decimal giftvoucher_base_hidden_tax_amount { get; set; }
        public decimal giftvoucher_hidden_tax_amount { get; set; }
        public decimal giftcredit_base_hidden_tax_amount { get; set; }
        public decimal giftcredit_hidden_tax_amount { get; set; }
        public decimal giftvoucher_base_shipping_hidden_tax_amount { get; set; }
        public decimal giftvoucher_shipping_hidden_tax_amount { get; set; }
        public decimal giftcredit_base_shipping_hidden_tax_amount { get; set; }
        public decimal giftcredit_shipping_hidden_tax_amount { get; set; }
    
        public virtual core_store core_store { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<crimson_pickqc_status> crimson_pickqc_status { get; set; }
        public virtual customer_entity customer_entity { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<downloadable_link_purchased> downloadable_link_purchased { get; set; }
        public virtual enterprise_customer_sales_flat_order enterprise_customer_sales_flat_order { get; set; }
        public virtual enterprise_sales_order_grid_archive enterprise_sales_order_grid_archive { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sales_flat_creditmemo> sales_flat_creditmemo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sales_flat_invoice> sales_flat_invoice { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sales_flat_order_address> sales_flat_order_address { get; set; }
        public virtual sales_flat_order_grid sales_flat_order_grid { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sales_flat_order_item> sales_flat_order_item { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sales_flat_order_payment> sales_flat_order_payment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sales_flat_order_status_history> sales_flat_order_status_history { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sales_flat_shipment> sales_flat_shipment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sales_payment_transaction> sales_payment_transaction { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sales_recurring_profile_order> sales_recurring_profile_order { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tm_orderattachment> tm_orderattachment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sales_billing_agreement> sales_billing_agreement { get; set; }
    }
}
