//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shopify.Admin.Console.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class sales_flat_shipment_track
    {
        public long entity_id { get; set; }
        public long parent_id { get; set; }
        public Nullable<decimal> weight { get; set; }
        public Nullable<decimal> qty { get; set; }
        public long order_id { get; set; }
        public string track_number { get; set; }
        public string description { get; set; }
        public string title { get; set; }
        public string carrier_code { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
    
        public virtual sales_flat_shipment sales_flat_shipment { get; set; }
    }
}
