//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shopify.Admin.Console.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class sales_flat_order_payment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public sales_flat_order_payment()
        {
            this.sales_payment_transaction = new HashSet<sales_payment_transaction>();
        }
    
        public long entity_id { get; set; }
        public long parent_id { get; set; }
        public Nullable<decimal> base_shipping_captured { get; set; }
        public Nullable<decimal> shipping_captured { get; set; }
        public Nullable<decimal> amount_refunded { get; set; }
        public Nullable<decimal> base_amount_paid { get; set; }
        public Nullable<decimal> amount_canceled { get; set; }
        public Nullable<decimal> base_amount_authorized { get; set; }
        public Nullable<decimal> base_amount_paid_online { get; set; }
        public Nullable<decimal> base_amount_refunded_online { get; set; }
        public Nullable<decimal> base_shipping_amount { get; set; }
        public Nullable<decimal> shipping_amount { get; set; }
        public Nullable<decimal> amount_paid { get; set; }
        public Nullable<decimal> amount_authorized { get; set; }
        public Nullable<decimal> base_amount_ordered { get; set; }
        public Nullable<decimal> base_shipping_refunded { get; set; }
        public Nullable<decimal> shipping_refunded { get; set; }
        public Nullable<decimal> base_amount_refunded { get; set; }
        public Nullable<decimal> amount_ordered { get; set; }
        public Nullable<decimal> base_amount_canceled { get; set; }
        public Nullable<int> quote_payment_id { get; set; }
        public string additional_data { get; set; }
        public string cc_exp_month { get; set; }
        public string cc_ss_start_year { get; set; }
        public string echeck_bank_name { get; set; }
        public string method { get; set; }
        public string cc_debug_request_body { get; set; }
        public string cc_secure_verify { get; set; }
        public string protection_eligibility { get; set; }
        public string cc_approval { get; set; }
        public string cc_last4 { get; set; }
        public string cc_status_description { get; set; }
        public string echeck_type { get; set; }
        public string cc_debug_response_serialized { get; set; }
        public string cc_ss_start_month { get; set; }
        public string echeck_account_type { get; set; }
        public string last_trans_id { get; set; }
        public string cc_cid_status { get; set; }
        public string cc_owner { get; set; }
        public string cc_type { get; set; }
        public string po_number { get; set; }
        public string cc_exp_year { get; set; }
        public string cc_status { get; set; }
        public string echeck_routing_number { get; set; }
        public string account_status { get; set; }
        public string anet_trans_method { get; set; }
        public string cc_debug_response_body { get; set; }
        public string cc_ss_issue { get; set; }
        public string echeck_account_name { get; set; }
        public string cc_avs_status { get; set; }
        public string cc_number_enc { get; set; }
        public string cc_trans_id { get; set; }
        public string paybox_request_number { get; set; }
        public string address_status { get; set; }
        public string additional_information { get; set; }
        public Nullable<long> tokenbase_id { get; set; }
        public string pos_payment_info { get; set; }
    
        public virtual sales_flat_order sales_flat_order { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sales_payment_transaction> sales_payment_transaction { get; set; }
    }
}
