//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shopify.Admin.Console.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class sales_flat_quote
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public sales_flat_quote()
        {
            this.sales_flat_quote_address = new HashSet<sales_flat_quote_address>();
            this.sales_flat_quote_item = new HashSet<sales_flat_quote_item>();
            this.sales_flat_quote_payment = new HashSet<sales_flat_quote_payment>();
            this.tm_orderattachment = new HashSet<tm_orderattachment>();
        }
    
        public long entity_id { get; set; }
        public int store_id { get; set; }
        public System.DateTime created_at { get; set; }
        public System.DateTime updated_at { get; set; }
        public Nullable<System.DateTime> converted_at { get; set; }
        public Nullable<int> is_active { get; set; }
        public Nullable<int> is_virtual { get; set; }
        public Nullable<int> is_multi_shipping { get; set; }
        public Nullable<long> items_count { get; set; }
        public Nullable<decimal> items_qty { get; set; }
        public Nullable<long> orig_order_id { get; set; }
        public Nullable<decimal> store_to_base_rate { get; set; }
        public Nullable<decimal> store_to_quote_rate { get; set; }
        public string base_currency_code { get; set; }
        public string store_currency_code { get; set; }
        public string quote_currency_code { get; set; }
        public Nullable<decimal> grand_total { get; set; }
        public Nullable<decimal> base_grand_total { get; set; }
        public string checkout_method { get; set; }
        public Nullable<long> customer_id { get; set; }
        public Nullable<long> customer_tax_class_id { get; set; }
        public Nullable<long> customer_group_id { get; set; }
        public string customer_email { get; set; }
        public string customer_prefix { get; set; }
        public string customer_firstname { get; set; }
        public string customer_middlename { get; set; }
        public string customer_lastname { get; set; }
        public string customer_suffix { get; set; }
        public Nullable<System.DateTime> customer_dob { get; set; }
        public string customer_note { get; set; }
        public Nullable<int> customer_note_notify { get; set; }
        public Nullable<int> customer_is_guest { get; set; }
        public string remote_ip { get; set; }
        public string applied_rule_ids { get; set; }
        public string reserved_order_id { get; set; }
        public string password_hash { get; set; }
        public string coupon_code { get; set; }
        public string global_currency_code { get; set; }
        public Nullable<decimal> base_to_global_rate { get; set; }
        public Nullable<decimal> base_to_quote_rate { get; set; }
        public string customer_taxvat { get; set; }
        public string customer_gender { get; set; }
        public Nullable<decimal> subtotal { get; set; }
        public Nullable<decimal> base_subtotal { get; set; }
        public Nullable<decimal> subtotal_with_discount { get; set; }
        public Nullable<decimal> base_subtotal_with_discount { get; set; }
        public Nullable<long> is_changed { get; set; }
        public short trigger_recollect { get; set; }
        public string ext_shipping_info { get; set; }
        public Nullable<int> gift_message_id { get; set; }
        public Nullable<int> is_persistent { get; set; }
        public Nullable<decimal> customer_balance_amount_used { get; set; }
        public Nullable<decimal> base_customer_bal_amount_used { get; set; }
        public Nullable<int> use_customer_balance { get; set; }
        public string gift_cards { get; set; }
        public Nullable<decimal> gift_cards_amount { get; set; }
        public Nullable<decimal> base_gift_cards_amount { get; set; }
        public Nullable<decimal> gift_cards_amount_used { get; set; }
        public Nullable<decimal> base_gift_cards_amount_used { get; set; }
        public Nullable<int> gw_id { get; set; }
        public Nullable<int> gw_allow_gift_receipt { get; set; }
        public Nullable<int> gw_add_card { get; set; }
        public Nullable<decimal> gw_base_price { get; set; }
        public Nullable<decimal> gw_price { get; set; }
        public Nullable<decimal> gw_items_base_price { get; set; }
        public Nullable<decimal> gw_items_price { get; set; }
        public Nullable<decimal> gw_card_base_price { get; set; }
        public Nullable<decimal> gw_card_price { get; set; }
        public Nullable<decimal> gw_base_tax_amount { get; set; }
        public Nullable<decimal> gw_tax_amount { get; set; }
        public Nullable<decimal> gw_items_base_tax_amount { get; set; }
        public Nullable<decimal> gw_items_tax_amount { get; set; }
        public Nullable<decimal> gw_card_base_tax_amount { get; set; }
        public Nullable<decimal> gw_card_tax_amount { get; set; }
        public Nullable<int> use_reward_points { get; set; }
        public Nullable<int> reward_points_balance { get; set; }
        public Nullable<decimal> base_reward_currency_amount { get; set; }
        public Nullable<decimal> reward_currency_amount { get; set; }
        public Nullable<System.DateTime> firecheckout_delivery_date { get; set; }
        public string firecheckout_delivery_timerange { get; set; }
        public string firecheckout_customer_comment { get; set; }
        public string tm_field1 { get; set; }
        public string tm_field2 { get; set; }
        public string tm_field3 { get; set; }
        public string tm_field4 { get; set; }
        public string tm_field5 { get; set; }
        public string auctaneapi_discounts { get; set; }
    
        public virtual core_store core_store { get; set; }
        public virtual enterprise_customer_sales_flat_quote enterprise_customer_sales_flat_quote { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sales_flat_quote_address> sales_flat_quote_address { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sales_flat_quote_item> sales_flat_quote_item { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sales_flat_quote_payment> sales_flat_quote_payment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tm_orderattachment> tm_orderattachment { get; set; }
    }
}
