//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shopify.Admin.Console.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class salesrule_label
    {
        public long label_id { get; set; }
        public long rule_id { get; set; }
        public int store_id { get; set; }
        public string label { get; set; }
    
        public virtual core_store core_store { get; set; }
        public virtual salesrule salesrule { get; set; }
    }
}
