//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shopify.Admin.Console.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class sales_flat_quote_payment
    {
        public long payment_id { get; set; }
        public long quote_id { get; set; }
        public System.DateTime created_at { get; set; }
        public System.DateTime updated_at { get; set; }
        public string method { get; set; }
        public string cc_type { get; set; }
        public string cc_number_enc { get; set; }
        public string cc_last4 { get; set; }
        public string cc_cid_enc { get; set; }
        public string cc_owner { get; set; }
        public Nullable<int> cc_exp_month { get; set; }
        public Nullable<int> cc_exp_year { get; set; }
        public string cc_ss_owner { get; set; }
        public Nullable<int> cc_ss_start_month { get; set; }
        public Nullable<int> cc_ss_start_year { get; set; }
        public string po_number { get; set; }
        public string additional_data { get; set; }
        public string cc_ss_issue { get; set; }
        public string additional_information { get; set; }
        public string paypal_payer_id { get; set; }
        public string paypal_payer_status { get; set; }
        public string paypal_correlation_id { get; set; }
        public Nullable<long> tokenbase_id { get; set; }
        public string pos_payment_info { get; set; }
    
        public virtual sales_flat_quote sales_flat_quote { get; set; }
    }
}
