//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shopify.Admin.Console.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class sales_flat_creditmemo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public sales_flat_creditmemo()
        {
            this.sales_flat_creditmemo_comment = new HashSet<sales_flat_creditmemo_comment>();
            this.sales_flat_creditmemo_item = new HashSet<sales_flat_creditmemo_item>();
        }
    
        public long entity_id { get; set; }
        public Nullable<int> store_id { get; set; }
        public Nullable<decimal> adjustment_positive { get; set; }
        public Nullable<decimal> base_shipping_tax_amount { get; set; }
        public Nullable<decimal> store_to_order_rate { get; set; }
        public Nullable<decimal> base_discount_amount { get; set; }
        public Nullable<decimal> base_to_order_rate { get; set; }
        public Nullable<decimal> grand_total { get; set; }
        public Nullable<decimal> base_adjustment_negative { get; set; }
        public Nullable<decimal> base_subtotal_incl_tax { get; set; }
        public Nullable<decimal> shipping_amount { get; set; }
        public Nullable<decimal> subtotal_incl_tax { get; set; }
        public Nullable<decimal> adjustment_negative { get; set; }
        public Nullable<decimal> base_shipping_amount { get; set; }
        public Nullable<decimal> store_to_base_rate { get; set; }
        public Nullable<decimal> base_to_global_rate { get; set; }
        public Nullable<decimal> base_adjustment { get; set; }
        public Nullable<decimal> base_subtotal { get; set; }
        public Nullable<decimal> discount_amount { get; set; }
        public Nullable<decimal> subtotal { get; set; }
        public Nullable<decimal> adjustment { get; set; }
        public Nullable<decimal> base_grand_total { get; set; }
        public Nullable<decimal> base_adjustment_positive { get; set; }
        public Nullable<decimal> base_tax_amount { get; set; }
        public Nullable<decimal> shipping_tax_amount { get; set; }
        public Nullable<decimal> tax_amount { get; set; }
        public long order_id { get; set; }
        public Nullable<int> email_sent { get; set; }
        public Nullable<int> creditmemo_status { get; set; }
        public Nullable<int> state { get; set; }
        public Nullable<int> shipping_address_id { get; set; }
        public Nullable<int> billing_address_id { get; set; }
        public Nullable<int> invoice_id { get; set; }
        public string store_currency_code { get; set; }
        public string order_currency_code { get; set; }
        public string base_currency_code { get; set; }
        public string global_currency_code { get; set; }
        public string transaction_id { get; set; }
        public string increment_id { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
        public Nullable<decimal> hidden_tax_amount { get; set; }
        public Nullable<decimal> base_hidden_tax_amount { get; set; }
        public Nullable<decimal> shipping_hidden_tax_amount { get; set; }
        public Nullable<decimal> base_shipping_hidden_tax_amnt { get; set; }
        public Nullable<decimal> shipping_incl_tax { get; set; }
        public Nullable<decimal> base_shipping_incl_tax { get; set; }
        public string discount_description { get; set; }
        public Nullable<decimal> base_customer_balance_amount { get; set; }
        public Nullable<decimal> customer_balance_amount { get; set; }
        public Nullable<decimal> bs_customer_bal_total_refunded { get; set; }
        public Nullable<decimal> customer_bal_total_refunded { get; set; }
        public Nullable<decimal> base_gift_cards_amount { get; set; }
        public Nullable<decimal> gift_cards_amount { get; set; }
        public Nullable<decimal> gw_base_price { get; set; }
        public Nullable<decimal> gw_price { get; set; }
        public Nullable<decimal> gw_items_base_price { get; set; }
        public Nullable<decimal> gw_items_price { get; set; }
        public Nullable<decimal> gw_card_base_price { get; set; }
        public Nullable<decimal> gw_card_price { get; set; }
        public Nullable<decimal> gw_base_tax_amount { get; set; }
        public Nullable<decimal> gw_tax_amount { get; set; }
        public Nullable<decimal> gw_items_base_tax_amount { get; set; }
        public Nullable<decimal> gw_items_tax_amount { get; set; }
        public Nullable<decimal> gw_card_base_tax_amount { get; set; }
        public Nullable<decimal> gw_card_tax_amount { get; set; }
        public Nullable<decimal> base_reward_currency_amount { get; set; }
        public Nullable<decimal> reward_currency_amount { get; set; }
        public Nullable<int> reward_points_balance { get; set; }
        public Nullable<int> reward_points_balance_refund { get; set; }
        public Nullable<decimal> affiliateplus_discount { get; set; }
        public Nullable<decimal> base_affiliateplus_discount { get; set; }
        public Nullable<decimal> base_affiliate_credit { get; set; }
        public Nullable<decimal> affiliate_credit { get; set; }
        public Nullable<decimal> payment_charge { get; set; }
        public Nullable<decimal> base_payment_charge { get; set; }
        public Nullable<decimal> base_gift_voucher_discount { get; set; }
        public Nullable<decimal> gift_voucher_discount { get; set; }
        public Nullable<decimal> base_use_gift_credit_amount { get; set; }
        public Nullable<decimal> use_gift_credit_amount { get; set; }
        public Nullable<decimal> giftcard_refund_amount { get; set; }
        public decimal giftvoucher_base_hidden_tax_amount { get; set; }
        public decimal giftvoucher_hidden_tax_amount { get; set; }
        public decimal giftcredit_base_hidden_tax_amount { get; set; }
        public decimal giftcredit_hidden_tax_amount { get; set; }
    
        public virtual core_store core_store { get; set; }
        public virtual enterprise_sales_creditmemo_grid_archive enterprise_sales_creditmemo_grid_archive { get; set; }
        public virtual sales_flat_order sales_flat_order { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sales_flat_creditmemo_comment> sales_flat_creditmemo_comment { get; set; }
        public virtual sales_flat_creditmemo_grid sales_flat_creditmemo_grid { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sales_flat_creditmemo_item> sales_flat_creditmemo_item { get; set; }
    }
}
