//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shopify.Admin.Console.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class sales_order_tax
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public sales_order_tax()
        {
            this.sales_order_tax_item = new HashSet<sales_order_tax_item>();
        }
    
        public long tax_id { get; set; }
        public long order_id { get; set; }
        public string code { get; set; }
        public string title { get; set; }
        public Nullable<decimal> percent { get; set; }
        public Nullable<decimal> amount { get; set; }
        public int priority { get; set; }
        public int position { get; set; }
        public Nullable<decimal> base_amount { get; set; }
        public short process { get; set; }
        public Nullable<decimal> base_real_amount { get; set; }
        public int hidden { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sales_order_tax_item> sales_order_tax_item { get; set; }
    }
}
