//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shopify.Admin.Console.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class sales_flat_quote_item_option
    {
        public long option_id { get; set; }
        public long item_id { get; set; }
        public long product_id { get; set; }
        public string code { get; set; }
        public string value { get; set; }
    
        public virtual sales_flat_quote_item sales_flat_quote_item { get; set; }
    }
}
