//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shopify.Admin.Console.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class salesrule_customer
    {
        public long rule_customer_id { get; set; }
        public long rule_id { get; set; }
        public long customer_id { get; set; }
        public int times_used { get; set; }
    
        public virtual customer_entity customer_entity { get; set; }
        public virtual salesrule salesrule { get; set; }
    }
}
