//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shopify.Admin.Console.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class sales_recurring_profile_order
    {
        public long link_id { get; set; }
        public long profile_id { get; set; }
        public long order_id { get; set; }
    
        public virtual sales_flat_order sales_flat_order { get; set; }
        public virtual sales_recurring_profile sales_recurring_profile { get; set; }
    }
}
