//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shopify.Admin.Console.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class sales_flat_order_grid
    {
        public long entity_id { get; set; }
        public string status { get; set; }
        public Nullable<int> store_id { get; set; }
        public string store_name { get; set; }
        public Nullable<long> customer_id { get; set; }
        public Nullable<decimal> base_grand_total { get; set; }
        public Nullable<decimal> base_total_paid { get; set; }
        public Nullable<decimal> grand_total { get; set; }
        public Nullable<decimal> total_paid { get; set; }
        public string increment_id { get; set; }
        public string base_currency_code { get; set; }
        public string order_currency_code { get; set; }
        public string shipping_name { get; set; }
        public string billing_name { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
    
        public virtual core_store core_store { get; set; }
        public virtual customer_entity customer_entity { get; set; }
        public virtual sales_flat_order sales_flat_order { get; set; }
    }
}
