//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shopify.Admin.Console.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class sales_order_status_state
    {
        public string status { get; set; }
        public string state { get; set; }
        public int is_default { get; set; }
    
        public virtual sales_order_status sales_order_status { get; set; }
    }
}
