//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shopify.Admin.Console.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class sales_billing_agreement
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public sales_billing_agreement()
        {
            this.sales_flat_order = new HashSet<sales_flat_order>();
        }
    
        public long agreement_id { get; set; }
        public long customer_id { get; set; }
        public string method_code { get; set; }
        public string reference_id { get; set; }
        public string status { get; set; }
        public System.DateTime created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
        public Nullable<int> store_id { get; set; }
        public string agreement_label { get; set; }
    
        public virtual core_store core_store { get; set; }
        public virtual customer_entity customer_entity { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sales_flat_order> sales_flat_order { get; set; }
    }
}
