//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shopify.Admin.Console.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class sales_payment_transaction
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public sales_payment_transaction()
        {
            this.sales_payment_transaction1 = new HashSet<sales_payment_transaction>();
        }
    
        public long transaction_id { get; set; }
        public Nullable<long> parent_id { get; set; }
        public long order_id { get; set; }
        public long payment_id { get; set; }
        public string txn_id { get; set; }
        public string parent_txn_id { get; set; }
        public string txn_type { get; set; }
        public int is_closed { get; set; }
        public byte[] additional_information { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
    
        public virtual sales_flat_order sales_flat_order { get; set; }
        public virtual sales_flat_order_payment sales_flat_order_payment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sales_payment_transaction> sales_payment_transaction1 { get; set; }
        public virtual sales_payment_transaction sales_payment_transaction2 { get; set; }
    }
}
