//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shopify.Admin.Console.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class sales_flat_shipment_comment
    {
        public long entity_id { get; set; }
        public long parent_id { get; set; }
        public Nullable<int> is_customer_notified { get; set; }
        public int is_visible_on_front { get; set; }
        public string comment { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
    
        public virtual sales_flat_shipment sales_flat_shipment { get; set; }
    }
}
