//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shopify.Admin.Console.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class sales_flat_quote_address
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public sales_flat_quote_address()
        {
            this.sales_flat_quote_address_item = new HashSet<sales_flat_quote_address_item>();
            this.sales_flat_quote_shipping_rate = new HashSet<sales_flat_quote_shipping_rate>();
        }
    
        public long address_id { get; set; }
        public long quote_id { get; set; }
        public System.DateTime created_at { get; set; }
        public System.DateTime updated_at { get; set; }
        public Nullable<long> customer_id { get; set; }
        public Nullable<short> save_in_address_book { get; set; }
        public Nullable<long> customer_address_id { get; set; }
        public string address_type { get; set; }
        public string email { get; set; }
        public string prefix { get; set; }
        public string firstname { get; set; }
        public string middlename { get; set; }
        public string lastname { get; set; }
        public string suffix { get; set; }
        public string company { get; set; }
        public string street { get; set; }
        public string city { get; set; }
        public string region { get; set; }
        public Nullable<long> region_id { get; set; }
        public string postcode { get; set; }
        public string country_id { get; set; }
        public string telephone { get; set; }
        public string fax { get; set; }
        public int same_as_billing { get; set; }
        public int free_shipping { get; set; }
        public int collect_shipping_rates { get; set; }
        public string shipping_method { get; set; }
        public string shipping_description { get; set; }
        public decimal weight { get; set; }
        public decimal subtotal { get; set; }
        public decimal base_subtotal { get; set; }
        public decimal subtotal_with_discount { get; set; }
        public decimal base_subtotal_with_discount { get; set; }
        public decimal tax_amount { get; set; }
        public decimal base_tax_amount { get; set; }
        public decimal shipping_amount { get; set; }
        public decimal base_shipping_amount { get; set; }
        public Nullable<decimal> shipping_tax_amount { get; set; }
        public Nullable<decimal> base_shipping_tax_amount { get; set; }
        public decimal discount_amount { get; set; }
        public decimal base_discount_amount { get; set; }
        public decimal grand_total { get; set; }
        public decimal base_grand_total { get; set; }
        public string customer_notes { get; set; }
        public string applied_taxes { get; set; }
        public string discount_description { get; set; }
        public Nullable<decimal> shipping_discount_amount { get; set; }
        public Nullable<decimal> base_shipping_discount_amount { get; set; }
        public Nullable<decimal> subtotal_incl_tax { get; set; }
        public Nullable<decimal> base_subtotal_total_incl_tax { get; set; }
        public Nullable<decimal> hidden_tax_amount { get; set; }
        public Nullable<decimal> base_hidden_tax_amount { get; set; }
        public Nullable<decimal> shipping_hidden_tax_amount { get; set; }
        public Nullable<decimal> base_shipping_hidden_tax_amnt { get; set; }
        public Nullable<decimal> shipping_incl_tax { get; set; }
        public Nullable<decimal> base_shipping_incl_tax { get; set; }
        public string vat_id { get; set; }
        public Nullable<short> vat_is_valid { get; set; }
        public string vat_request_id { get; set; }
        public string vat_request_date { get; set; }
        public Nullable<short> vat_request_success { get; set; }
        public Nullable<int> gift_message_id { get; set; }
        public Nullable<decimal> base_customer_balance_amount { get; set; }
        public Nullable<decimal> customer_balance_amount { get; set; }
        public Nullable<decimal> gift_cards_amount { get; set; }
        public Nullable<decimal> base_gift_cards_amount { get; set; }
        public string gift_cards { get; set; }
        public string used_gift_cards { get; set; }
        public Nullable<int> giftregistry_item_id { get; set; }
        public Nullable<int> gw_id { get; set; }
        public Nullable<int> gw_allow_gift_receipt { get; set; }
        public Nullable<int> gw_add_card { get; set; }
        public Nullable<decimal> gw_base_price { get; set; }
        public Nullable<decimal> gw_price { get; set; }
        public Nullable<decimal> gw_items_base_price { get; set; }
        public Nullable<decimal> gw_items_price { get; set; }
        public Nullable<decimal> gw_card_base_price { get; set; }
        public Nullable<decimal> gw_card_price { get; set; }
        public Nullable<decimal> gw_base_tax_amount { get; set; }
        public Nullable<decimal> gw_tax_amount { get; set; }
        public Nullable<decimal> gw_items_base_tax_amount { get; set; }
        public Nullable<decimal> gw_items_tax_amount { get; set; }
        public Nullable<decimal> gw_card_base_tax_amount { get; set; }
        public Nullable<decimal> gw_card_tax_amount { get; set; }
        public Nullable<int> reward_points_balance { get; set; }
        public Nullable<decimal> base_reward_currency_amount { get; set; }
        public Nullable<decimal> reward_currency_amount { get; set; }
        public Nullable<decimal> payment_charge { get; set; }
        public Nullable<decimal> base_payment_charge { get; set; }
        public Nullable<decimal> base_paypalfee_amount { get; set; }
        public Nullable<decimal> paypalfee_amount { get; set; }
    
        public virtual enterprise_customer_sales_flat_quote_address enterprise_customer_sales_flat_quote_address { get; set; }
        public virtual sales_flat_quote sales_flat_quote { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sales_flat_quote_address_item> sales_flat_quote_address_item { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sales_flat_quote_shipping_rate> sales_flat_quote_shipping_rate { get; set; }
    }
}
