//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shopify.Admin.Console.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class sales_flat_creditmemo_item
    {
        public long entity_id { get; set; }
        public long parent_id { get; set; }
        public Nullable<decimal> base_price { get; set; }
        public Nullable<decimal> tax_amount { get; set; }
        public Nullable<decimal> base_row_total { get; set; }
        public Nullable<decimal> discount_amount { get; set; }
        public Nullable<decimal> row_total { get; set; }
        public Nullable<decimal> base_discount_amount { get; set; }
        public Nullable<decimal> price_incl_tax { get; set; }
        public Nullable<decimal> base_tax_amount { get; set; }
        public Nullable<decimal> base_price_incl_tax { get; set; }
        public Nullable<decimal> qty { get; set; }
        public Nullable<decimal> base_cost { get; set; }
        public Nullable<decimal> price { get; set; }
        public Nullable<decimal> base_row_total_incl_tax { get; set; }
        public Nullable<decimal> row_total_incl_tax { get; set; }
        public Nullable<int> product_id { get; set; }
        public Nullable<int> order_item_id { get; set; }
        public string additional_data { get; set; }
        public string description { get; set; }
        public string sku { get; set; }
        public string name { get; set; }
        public Nullable<decimal> hidden_tax_amount { get; set; }
        public Nullable<decimal> base_hidden_tax_amount { get; set; }
        public Nullable<decimal> weee_tax_disposition { get; set; }
        public Nullable<decimal> weee_tax_row_disposition { get; set; }
        public Nullable<decimal> base_weee_tax_disposition { get; set; }
        public Nullable<decimal> base_weee_tax_row_disposition { get; set; }
        public string weee_tax_applied { get; set; }
        public Nullable<decimal> base_weee_tax_applied_amount { get; set; }
        public Nullable<decimal> base_weee_tax_applied_row_amnt { get; set; }
        public Nullable<decimal> weee_tax_applied_amount { get; set; }
        public Nullable<decimal> weee_tax_applied_row_amount { get; set; }
        public Nullable<short> affiliateplus_commission_flag { get; set; }
        public Nullable<decimal> base_gift_voucher_discount { get; set; }
        public Nullable<decimal> gift_voucher_discount { get; set; }
        public Nullable<decimal> base_use_gift_credit_amount { get; set; }
        public Nullable<decimal> use_gift_credit_amount { get; set; }
        public Nullable<decimal> giftcard_refund_amount { get; set; }
    
        public virtual sales_flat_creditmemo sales_flat_creditmemo { get; set; }
    }
}
