//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shopify.Admin.Console.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class seosuite_report_category
    {
        public long entity_id { get; set; }
        public long category_id { get; set; }
        public int store_id { get; set; }
        public byte level { get; set; }
        public string url_path { get; set; }
        public string name { get; set; }
        public string prepared_name { get; set; }
        public int name_dupl { get; set; }
        public string meta_title { get; set; }
        public string prepared_meta_title { get; set; }
        public byte meta_title_len { get; set; }
        public int meta_title_dupl { get; set; }
        public int meta_descr_len { get; set; }
    }
}
