//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shopify.Admin.Console.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class shipping_tablerate
    {
        public long pk { get; set; }
        public int website_id { get; set; }
        public string dest_country_id { get; set; }
        public int dest_region_id { get; set; }
        public string dest_zip { get; set; }
        public string condition_name { get; set; }
        public decimal condition_value { get; set; }
        public decimal price { get; set; }
        public decimal cost { get; set; }
    }
}
