//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shopify.Admin.Console.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class springbot_trackable
    {
        public long id { get; set; }
        public string email { get; set; }
        public string type { get; set; }
        public string value { get; set; }
        public Nullable<int> quote_id { get; set; }
        public Nullable<int> order_id { get; set; }
        public Nullable<int> customer_id { get; set; }
        public System.DateTime created_at { get; set; }
    }
}
