//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shopify.Admin.Console.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class springbot_cron_count
    {
        public long id { get; set; }
        public string entity { get; set; }
        public int store_id { get; set; }
        public string harvest_id { get; set; }
        public System.DateTime created_at { get; set; }
        public Nullable<System.DateTime> completed { get; set; }
        public long count { get; set; }
    }
}
