//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shopify.Admin.Console.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class springbot_cron_queue
    {
        public long id { get; set; }
        public string method { get; set; }
        public string args { get; set; }
        public int store_id { get; set; }
        public string command_hash { get; set; }
        public string queue { get; set; }
        public long priority { get; set; }
        public long attempts { get; set; }
        public Nullable<System.DateTime> run_at { get; set; }
        public Nullable<System.DateTime> locked_at { get; set; }
        public string locked_by { get; set; }
        public string error { get; set; }
        public Nullable<System.DateTime> next_run_at { get; set; }
        public System.DateTime created_at { get; set; }
    }
}
