//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shopify.Admin.Console.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class springbot_actions
    {
        public long id { get; set; }
        public string type { get; set; }
        public int store_id { get; set; }
        public string visitor_ip { get; set; }
        public string page_url { get; set; }
        public string sku { get; set; }
        public string sku_fulfillment { get; set; }
        public Nullable<long> quantity { get; set; }
        public Nullable<long> purchase_id { get; set; }
        public Nullable<long> quote_id { get; set; }
        public Nullable<long> category_id { get; set; }
        public string locked_by { get; set; }
        public Nullable<System.DateTime> locked_at { get; set; }
        public System.DateTime created_at { get; set; }
    }
}
