//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shopify.Admin.Console.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tag
    {
        public long tag_id { get; set; }
        public string name { get; set; }
        public short status { get; set; }
        public Nullable<long> first_customer_id { get; set; }
        public Nullable<int> first_store_id { get; set; }
    
        public virtual core_store core_store { get; set; }
        public virtual customer_entity customer_entity { get; set; }
    }
}
