//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shopify.Admin.Console.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tax_calculation_rate_title
    {
        public int tax_calculation_rate_title_id { get; set; }
        public int tax_calculation_rate_id { get; set; }
        public int store_id { get; set; }
        public string value { get; set; }
    
        public virtual core_store core_store { get; set; }
        public virtual tax_calculation_rate tax_calculation_rate { get; set; }
    }
}
