//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shopify.Admin.Console.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tax_calculation_rate
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tax_calculation_rate()
        {
            this.tax_calculation = new HashSet<tax_calculation>();
            this.tax_calculation_rate_title = new HashSet<tax_calculation_rate_title>();
        }
    
        public int tax_calculation_rate_id { get; set; }
        public string tax_country_id { get; set; }
        public int tax_region_id { get; set; }
        public string tax_postcode { get; set; }
        public string code { get; set; }
        public decimal rate { get; set; }
        public Nullable<short> zip_is_range { get; set; }
        public Nullable<long> zip_from { get; set; }
        public Nullable<long> zip_to { get; set; }
        public byte ebizmarts_pos_synch { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tax_calculation> tax_calculation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tax_calculation_rate_title> tax_calculation_rate_title { get; set; }
    }
}
