//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shopify.Admin.Console.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tax_calculation
    {
        public int tax_calculation_id { get; set; }
        public int tax_calculation_rate_id { get; set; }
        public int tax_calculation_rule_id { get; set; }
        public short customer_tax_class_id { get; set; }
        public short product_tax_class_id { get; set; }
    
        public virtual tax_calculation_rate tax_calculation_rate { get; set; }
        public virtual tax_calculation_rule tax_calculation_rule { get; set; }
        public virtual tax_class tax_class { get; set; }
        public virtual tax_class tax_class1 { get; set; }
    }
}
