//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shopify.Admin.Console.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class warehouse_stock_movements
    {
        public long stockmov_id { get; set; }
        public long stockmov_depot_id { get; set; }
        public long stockmov_product_id { get; set; }
        public Nullable<long> stockmov_document_id { get; set; }
        public long stockmov_movtype_id { get; set; }
        public string stockmov_sign { get; set; }
        public decimal stockmov_quantity { get; set; }
        public string stockmov_description { get; set; }
        public Nullable<long> stockmov_related_id { get; set; }
        public System.DateTime stockmov_created_at { get; set; }
    
        public virtual warehouse_movtype warehouse_movtype { get; set; }
    }
}
