//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shopify.Admin.Console.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class warehouse_stock_movements_index
    {
        public long stockmovindex_id { get; set; }
        public long stockmovindex_depot_id { get; set; }
        public long stockmovindex_product_id { get; set; }
        public decimal stockmovindex_quantity { get; set; }
        public int stockmovindex_manage_stock { get; set; }
        public System.DateTime stockmovindex_created_at { get; set; }
    }
}
