//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shopify.Admin.Console.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class weee_tax
    {
        public int value_id { get; set; }
        public int website_id { get; set; }
        public long entity_id { get; set; }
        public string country { get; set; }
        public decimal value { get; set; }
        public string state { get; set; }
        public int attribute_id { get; set; }
        public int entity_type_id { get; set; }
    
        public virtual catalog_product_entity catalog_product_entity { get; set; }
        public virtual core_website core_website { get; set; }
        public virtual directory_country directory_country { get; set; }
        public virtual eav_attribute eav_attribute { get; set; }
    }
}
