//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shopify.Admin.Console.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class widget_instance
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public widget_instance()
        {
            this.widget_instance_page = new HashSet<widget_instance_page>();
        }
    
        public long instance_id { get; set; }
        public string instance_type { get; set; }
        public string package_theme { get; set; }
        public string title { get; set; }
        public string store_ids { get; set; }
        public string widget_parameters { get; set; }
        public int sort_order { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<widget_instance_page> widget_instance_page { get; set; }
    }
}
