//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shopify.Admin.Console.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class widget_instance_page
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public widget_instance_page()
        {
            this.core_layout_update = new HashSet<core_layout_update>();
        }
    
        public long page_id { get; set; }
        public long instance_id { get; set; }
        public string page_group { get; set; }
        public string layout_handle { get; set; }
        public string block_reference { get; set; }
        public string page_for { get; set; }
        public string entities { get; set; }
        public string page_template { get; set; }
    
        public virtual widget_instance widget_instance { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<core_layout_update> core_layout_update { get; set; }
    }
}
