//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shopify.Admin.Console.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class wishlist_item
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public wishlist_item()
        {
            this.wishlist_item_option = new HashSet<wishlist_item_option>();
        }
    
        public long wishlist_item_id { get; set; }
        public long wishlist_id { get; set; }
        public long product_id { get; set; }
        public Nullable<int> store_id { get; set; }
        public Nullable<System.DateTime> added_at { get; set; }
        public string description { get; set; }
        public decimal qty { get; set; }
    
        public virtual catalog_product_entity catalog_product_entity { get; set; }
        public virtual core_store core_store { get; set; }
        public virtual wishlist wishlist { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<wishlist_item_option> wishlist_item_option { get; set; }
    }
}
