//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shopify.Admin.Console.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class wishlist
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public wishlist()
        {
            this.wishlist_item = new HashSet<wishlist_item>();
        }
    
        public long wishlist_id { get; set; }
        public long customer_id { get; set; }
        public int shared { get; set; }
        public string sharing_code { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
        public string name { get; set; }
        public Nullable<short> visibility { get; set; }
    
        public virtual customer_entity customer_entity { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<wishlist_item> wishlist_item { get; set; }
    }
}
