//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shopify.Admin.Console.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class wordpress_association
    {
        public long assoc_id { get; set; }
        public long type_id { get; set; }
        public long object_id { get; set; }
        public long wordpress_object_id { get; set; }
        public long position { get; set; }
        public int store_id { get; set; }
    
        public virtual core_store core_store { get; set; }
        public virtual wordpress_association_type wordpress_association_type { get; set; }
    }
}
