//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shopify.Admin.Console.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class xmlconnect_images
    {
        public long image_id { get; set; }
        public int application_id { get; set; }
        public string image_file { get; set; }
        public string image_type { get; set; }
        public long order { get; set; }
    
        public virtual xmlconnect_application xmlconnect_application { get; set; }
    }
}
